import 'dart:async';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/app_strings.dart';
import '../../../core/constants/locale_controller.dart';
import '../../../services/auth_service.dart';
import '../../../services/chat_service.dart';
import '../../../services/booking_service.dart';
import '../../../services/user_service.dart';
import '../models/message.dart';
import '../models/app_user.dart';

class ChatScreen extends StatefulWidget{final String bookingId;const ChatScreen({super.key,required this.bookingId});@override State<ChatScreen> createState()=>_ChatScreenState();}
class _ChatScreenState extends State<ChatScreen>{final _messageController=TextEditingController();final _scrollController=ScrollController();final _chatService=ChatService();String? _chatId;String? _otherUserId;AppUser? _otherUser;bool _isLoading=true;bool _isSending=false;String? _errorMessage;String t(String k)=>AppStrings.t(k);bool get en=>LocaleController.instance.isEnglish;String tx(String ar,String english)=>en?english:ar;
 @override void initState(){super.initState();_initChat();}
 @override void dispose(){_messageController.dispose();_scrollController.dispose();super.dispose();}
 Future<void> _initChat()async{setState((){_isLoading=true;_errorMessage=null;});try{final booking=await BookingService().getBooking(widget.bookingId);if(booking==null){if(mounted)setState((){_isLoading=false;_errorMessage=t('booking_not_found');});return;}final user=AuthService().currentUser;if(user==null){if(mounted)setState((){_isLoading=false;_errorMessage=tx('يرجى تسجيل الدخول','Please log in');});return;}final currentUserId=user.uid;final otherUserId=currentUserId==booking.clientId?booking.nurseId:booking.clientId;final otherUser=await UserService().getUser(otherUserId);final chatId=await _chatService.getOrCreateChat(widget.bookingId,booking.clientId,booking.nurseId);if(!mounted)return;setState((){_chatId=chatId;_otherUserId=otherUserId;_otherUser=otherUser;_isLoading=false;});unawaited(_chatService.markMessagesAsSeen(chatId,currentUserId));}catch(_){if(mounted)setState((){_isLoading=false;_errorMessage=tx('تعذر فتح المحادثة','Unable to open the conversation');});}}
 Future<void> _sendMessage()async{final text=_messageController.text.trim();if(text.isEmpty||_chatId==null||_otherUserId==null||_isSending)return;final user=AuthService().currentUser;if(user==null)return;setState(()=>_isSending=true);_messageController.clear();try{await _chatService.sendMessage(_chatId!,user.uid,_otherUserId!,text);if(_scrollController.hasClients)_scrollController.animateTo(0,duration:const Duration(milliseconds:250),curve:Curves.easeOut);}catch(_){if(mounted){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(tx('تعذر إرسال الرسالة، حاول مرة أخرى','Unable to send the message. Please try again'))));_messageController.text=text;}}finally{if(mounted)setState(()=>_isSending=false);}}
 @override Widget build(BuildContext context){final otherName=_otherUser?.name.trim().isNotEmpty==true?_otherUser!.name.trim():tx('محادثة','Conversation');return Scaffold(backgroundColor:AppColors.background,appBar:AppBar(titleSpacing:0,title:Row(children:[CircleAvatar(radius:18,backgroundColor:AppColors.primaryLight,backgroundImage:(_otherUser?.photoUrl?.isNotEmpty??false)?NetworkImage(_otherUser!.photoUrl!):null,child:(_otherUser?.photoUrl?.isNotEmpty??false)?null:const Icon(Icons.person_outline)),const SizedBox(width:10),Expanded(child:Text(otherName,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:16,fontWeight:FontWeight.w700)))])),body:_isLoading?const Center(child:CircularProgressIndicator()):_chatId==null?Center(child:Text(_errorMessage??tx('لا يمكن بدء المحادثة','Unable to start the conversation'))):Column(children:[Expanded(child:StreamBuilder<List<Message>>(stream:_chatService.getMessages(_chatId!),builder:(context,snapshot){if(snapshot.connectionState==ConnectionState.waiting&&!snapshot.hasData)return const Center(child:CircularProgressIndicator());if(snapshot.hasError)return Center(child:Text(tx('حدث خطأ أثناء تحميل الرسائل','An error occurred while loading messages')));final messages=snapshot.data??const <Message>[];if(messages.isEmpty)return Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.chat_bubble_outline,size:48,color:AppColors.textSecondary),const SizedBox(height:10),Text('${tx('ابدأ المحادثة مع','Start the conversation with')} $otherName',textAlign:TextAlign.center)])));final reversed=messages.reversed.toList(growable:false);final myId=AuthService().currentUser?.uid;return ListView.builder(controller:_scrollController,reverse:true,padding:const EdgeInsets.all(12),itemCount:reversed.length,itemBuilder:(context,index){final msg=reversed[index];return _MessageBubble(message:msg,isMe:msg.senderId==myId);});})),SafeArea(top:false,child:Padding(padding:const EdgeInsets.fromLTRB(8,6,8,8),child:Row(crossAxisAlignment:CrossAxisAlignment.end,children:[Expanded(child:TextField(controller:_messageController,minLines:1,maxLines:4,textInputAction:TextInputAction.send,onSubmitted:(_)=>_sendMessage(),decoration:InputDecoration(hintText:tx('اكتب رسالتك...','Write your message...'),filled:true,fillColor:Colors.white,contentPadding:const EdgeInsets.symmetric(horizontal:16,vertical:10),border:OutlineInputBorder(borderRadius:BorderRadius.circular(24),borderSide:BorderSide(color:Colors.grey.shade300))))),const SizedBox(width:8),CircleAvatar(radius:22,backgroundColor:AppColors.primary,child:_isSending?const SizedBox(width:18,height:18,child:CircularProgressIndicator(color:Colors.white,strokeWidth:2)):IconButton(icon:const Icon(Icons.send,color:Colors.white,size:20),onPressed:_sendMessage))])))]);}
}
class _MessageBubble extends StatelessWidget{final Message message;final bool isMe;const _MessageBubble({required this.message,required this.isMe});@override Widget build(BuildContext context){final en=LocaleController.instance.isEnglish;final time=DateFormat.jm(en?'en_US':'ar_EG').format(message.createdAt);return Align(alignment:isMe?AlignmentDirectional.centerEnd:AlignmentDirectional.centerStart,child:Container(constraints:BoxConstraints(maxWidth:MediaQuery.of(context).size.width*.75),margin:const EdgeInsets.symmetric(vertical:4),padding:const EdgeInsets.symmetric(horizontal:14,vertical:10),decoration:BoxDecoration(color:isMe?AppColors.primary:Colors.white,borderRadius:BorderRadius.only(topLeft:const Radius.circular(16),topRight:const Radius.circular(16),bottomLeft:Radius.circular(isMe?16:4),bottomRight:Radius.circular(isMe?4:16)),boxShadow:[BoxShadow(color:Colors.black.withValues(alpha:.05),blurRadius:4,offset:const Offset(0,1))]),child:Column(crossAxisAlignment:CrossAxisAlignment.end,mainAxisSize:MainAxisSize.min,children:[Text(message.text,style:TextStyle(color:isMe?Colors.white:AppColors.textPrimary,fontSize:15)),const SizedBox(height:4),Text(time,style:TextStyle(fontSize:10,color:isMe?Colors.white70:AppColors.textSecondary))]));}}
