// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXg9ER9mmYfxbBgj4dm-nEPCkahj_oBT4',
    appId: '1:249037491375:web:2c8e99e32be277032a585a',
    messagingSenderId: '249037491375',
    projectId: 'homecare-16c84',
    authDomain: 'homecare-16c84.firebaseapp.com',
    storageBucket: 'homecare-16c84.firebasestorage.app',
    measurementId: 'G-ZGE2RNN70R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbqXbhxepFZboUCkmYydcD7vTStZ74ZTI',
    appId: '1:249037491375:android:455c6f755f01c5ee2a585a',
    messagingSenderId: '249037491375',
    projectId: 'homecare-16c84',
    storageBucket: 'homecare-16c84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt6afrNyPkH_oREqWzb_ew4zJ5DWTS_hc',
    appId: '1:249037491375:ios:93d7493874f631e32a585a',
    messagingSenderId: '249037491375',
    projectId: 'homecare-16c84',
    storageBucket: 'homecare-16c84.firebasestorage.app',
    iosBundleId: 'com.example.saas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt6afrNyPkH_oREqWzb_ew4zJ5DWTS_hc',
    appId: '1:249037491375:ios:93d7493874f631e32a585a',
    messagingSenderId: '249037491375',
    projectId: 'homecare-16c84',
    storageBucket: 'homecare-16c84.firebasestorage.app',
    iosBundleId: 'com.example.saas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXg9ER9mmYfxbBgj4dm-nEPCkahj_oBT4',
    appId: '1:249037491375:web:d7af26757c6e43e22a585a',
    messagingSenderId: '249037491375',
    projectId: 'homecare-16c84',
    authDomain: 'homecare-16c84.firebaseapp.com',
    storageBucket: 'homecare-16c84.firebasestorage.app',
    measurementId: 'G-02FHMF4GMG',
  );
}
