import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/app_strings.dart';
import '../../../services/auth_service.dart';
import '../../../services/user_service.dart';
import 'package:firebase_auth/firebase_auth.dart';

class LoginScreen extends StatefulWidget { const LoginScreen({super.key}); @override State<LoginScreen> createState()=>_LoginScreenState(); }
class _LoginScreenState extends State<LoginScreen>{
 final _formKey=GlobalKey<FormState>(); final _emailController=TextEditingController(); final _passwordController=TextEditingController(); bool _obscurePassword=true; bool _isLoading=false; String? _errorMessage;
 String t(String k)=>AppStrings.t(k);
 Future<void> _login() async {if(!_formKey.currentState!.validate())return;setState((){_isLoading=true;_errorMessage=null;});try{final cred=await AuthService().login(_emailController.text.trim(),_passwordController.text.trim());final user=cred.user;if(user!=null){final appUser=await UserService().getUser(user.uid);if(appUser==null){if(mounted)context.go('/role');return;}if(appUser.role=='client'){if(mounted)context.go('/client/home');}else if(appUser.role=='nurse'){if(mounted)context.go('/nurse/home');}else{setState(()=>_errorMessage=t('error_generic'));}}}on FirebaseAuthException catch(e){String msg=t('error_generic');if(e.code=='user-not-found'||e.code=='wrong-password')msg=t('invalid_credentials');else if(e.code=='invalid-email')msg=t('invalid_email');else if(e.code=='too-many-requests')msg=t('too_many_requests');setState(()=>_errorMessage=msg);}catch(_){setState(()=>_errorMessage=t('something_wrong'));}finally{if(mounted)setState(()=>_isLoading=false);}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(t('login_title')),backgroundColor:Colors.white,foregroundColor:AppColors.textPrimary),body:Padding(padding:const EdgeInsets.all(24),child:Form(key:_formKey,child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Icon(Icons.health_and_safety,size:80,color:AppColors.primary),const SizedBox(height:16),Text(t('welcome_back'),style:const TextStyle(fontSize:24,fontWeight:FontWeight.bold)),const SizedBox(height:8),Text(t('login_subtitle'),style:const TextStyle(color:AppColors.textSecondary)),const SizedBox(height:32),TextFormField(controller:_emailController,keyboardType:TextInputType.emailAddress,decoration:InputDecoration(labelText:t('email'),prefixIcon:const Icon(Icons.email)),validator:(v)=>v!.isEmpty?t('email_required'):null),const SizedBox(height:16),TextFormField(controller:_passwordController,obscureText:_obscurePassword,decoration:InputDecoration(labelText:t('password'),prefixIcon:const Icon(Icons.lock),suffixIcon:IconButton(icon:Icon(_obscurePassword?Icons.visibility:Icons.visibility_off),onPressed:()=>setState(()=>_obscurePassword=!_obscurePassword))),validator:(v)=>v!.length<8?t('password_min'):null),const SizedBox(height:8),Align(alignment:AlignmentDirectional.centerEnd,child:TextButton(onPressed:()async{if(_emailController.text.isNotEmpty){try{await AuthService().resetPassword(_emailController.text.trim());if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(t('reset_sent'))));}catch(_){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(t('error_generic'))));}}else{ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(t('email_first'))));}},child:Text(t('forgot_password')))),if(_errorMessage!=null)...[const SizedBox(height:8),Text(_errorMessage!,style:const TextStyle(color:AppColors.error))],const SizedBox(height:16),ElevatedButton(onPressed:_isLoading?null:_login,child:_isLoading?const SizedBox(width:20,height:20,child:CircularProgressIndicator(color:Colors.white,strokeWidth:2)):Text(t('login_button'))),const SizedBox(height:16),Row(mainAxisAlignment:MainAxisAlignment.center,children:[Text(t('no_account')),TextButton(onPressed:()=>context.go('/role'),child:Text(t('register_new'),style:const TextStyle(color:AppColors.primary)))])]))));
 @override void dispose(){_emailController.dispose();_passwordController.dispose();super.dispose();}
}
