import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/app_strings.dart';
import '../../../services/auth_service.dart';
import '../../../services/user_service.dart';
import '../../../services/shared_preferences_service.dart';
import '../../shared/models/app_user.dart';
import 'package:firebase_auth/firebase_auth.dart';

class RegisterScreen extends StatefulWidget{const RegisterScreen({super.key});@override State<RegisterScreen> createState()=>_RegisterScreenState();}
class _RegisterScreenState extends State<RegisterScreen>{final _formKey=GlobalKey<FormState>();final _nameController=TextEditingController();final _phoneController=TextEditingController();final _emailController=TextEditingController();final _passwordController=TextEditingController();final _confirmPasswordController=TextEditingController();bool _obscurePassword=true;bool _isLoading=false;String? _errorMessage;String t(String k)=>AppStrings.t(k);
 Future<void> _register()async{if(!_formKey.currentState!.validate())return;setState((){_isLoading=true;_errorMessage=null;});final prefs=SharedPreferencesService();final role=prefs.getSelectedRole();if(role==null||(role!='client'&&role!='nurse')){setState((){_errorMessage=t('role_selection_title');_isLoading=false;});return;}try{final cred=await AuthService().register(_emailController.text.trim(),_passwordController.text.trim());final user=cred.user!;final appUser=AppUser(uid:user.uid,role:role,name:_nameController.text.trim(),phone:_phoneController.text.trim(),email:_emailController.text.trim(),createdAt:DateTime.now(),updatedAt:DateTime.now());await UserService().createUser(appUser);await prefs.clearTempPreferences();if(mounted)context.go(role=='client'?'/client/home':'/nurse/home');}on FirebaseAuthException catch(e){String msg=t('error_generic');if(e.code=='email-already-in-use')msg=t('error_generic');else if(e.code=='weak-password')msg=t('password_min');else if(e.code=='invalid-email')msg=t('invalid_email');if(mounted)setState(()=>_errorMessage=msg);}catch(_){if(mounted)setState(()=>_errorMessage=t('something_wrong'));}finally{if(mounted)setState(()=>_isLoading=false);}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(t('register_title')),backgroundColor:Colors.white,foregroundColor:AppColors.textPrimary),body:Padding(padding:const EdgeInsets.all(24),child:Form(key:_formKey,child:SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Icon(Icons.person_add,size:60,color:AppColors.primary),const SizedBox(height:16),Text(t('register_title'),style:const TextStyle(fontSize:24,fontWeight:FontWeight.bold)),const SizedBox(height:8),Text(t('get_started'),style:const TextStyle(color:AppColors.textSecondary)),const SizedBox(height:24),TextFormField(controller:_nameController,decoration:InputDecoration(labelText:t('full_name'),prefixIcon:const Icon(Icons.person)),validator:(v)=>v!.trim().length<2?t('required_field'):null),const SizedBox(height:16),TextFormField(controller:_phoneController,keyboardType:TextInputType.phone,decoration:InputDecoration(labelText:t('phone_number'),prefixIcon:const Icon(Icons.phone)),validator:(v)=>v!.trim().length<10?t('phone_invalid'):null),const SizedBox(height:16),TextFormField(controller:_emailController,keyboardType:TextInputType.emailAddress,decoration:InputDecoration(labelText:t('email'),prefixIcon:const Icon(Icons.email)),validator:(v)=>v!.trim().isEmpty?t('email_required'):null),const SizedBox(height:16),TextFormField(controller:_passwordController,obscureText:_obscurePassword,decoration:InputDecoration(labelText:t('password'),prefixIcon:const Icon(Icons.lock),suffixIcon:IconButton(icon:Icon(_obscurePassword?Icons.visibility:Icons.visibility_off),onPressed:()=>setState(()=>_obscurePassword=!_obscurePassword))),validator:(v)=>v!.length<8?t('password_min'):null),const SizedBox(height:16),TextFormField(controller:_confirmPasswordController,obscureText:_obscurePassword,decoration:InputDecoration(labelText:t('password'),prefixIcon:const Icon(Icons.check)),validator:(v)=>v!=_passwordController.text?t('error_generic'):null),if(_errorMessage!=null)...[const SizedBox(height:8),Text(_errorMessage!,style:const TextStyle(color:AppColors.error))],const SizedBox(height:24),ElevatedButton(onPressed:_isLoading?null:_register,child:_isLoading?const SizedBox(width:20,height:20,child:CircularProgressIndicator(color:Colors.white,strokeWidth:2)):Text(t('register_button'))),const SizedBox(height:16),Row(mainAxisAlignment:MainAxisAlignment.center,children:[Text(t('have_account')),TextButton(onPressed:()=>context.go('/login'),child:Text(t('login_now'),style:const TextStyle(color:AppColors.primary)))])]))));
 @override void dispose(){_nameController.dispose();_phoneController.dispose();_emailController.dispose();_passwordController.dispose();_confirmPasswordController.dispose();super.dispose();}}
