import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/app_strings.dart';
import '../../../services/shared_preferences_service.dart';

class RoleSelectionScreen extends StatefulWidget { const RoleSelectionScreen({super.key}); @override State<RoleSelectionScreen> createState()=>_RoleSelectionScreenState(); }
class _RoleSelectionScreenState extends State<RoleSelectionScreen>{ String? _selectedRole; String t(String k)=>AppStrings.t(k);
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(t('role_selection_title')),backgroundColor:Colors.white,foregroundColor:AppColors.textPrimary),body:Padding(padding:const EdgeInsets.all(24),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text(t('role_question'),style:const TextStyle(fontSize:24,fontWeight:FontWeight.bold)),const SizedBox(height:8),Text(t('role_subtitle'),style:const TextStyle(color:AppColors.textSecondary)),const SizedBox(height:32),Expanded(child:Column(children:[_buildRoleCard(title:t('role_client'),description:t('role_client_desc'),icon:Icons.family_restroom,role:'client'),const SizedBox(height:16),_buildRoleCard(title:t('role_nurse'),description:t('role_nurse_desc'),icon:Icons.medical_services,role:'nurse')])),ElevatedButton(onPressed:_selectedRole==null?null:()async{await SharedPreferencesService().setSelectedRole(_selectedRole!);if(mounted)context.go('/register');},child:Text(t('next'))),const SizedBox(height:16)])));
 Widget _buildRoleCard({required String title,required String description,required IconData icon,required String role}){final selected=_selectedRole==role;return GestureDetector(onTap:()=>setState(()=>_selectedRole=role),child:Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:selected?AppColors.primary.withOpacity(.1):Colors.white,borderRadius:BorderRadius.circular(16),border:Border.all(color:selected?AppColors.primary:Colors.grey.shade300,width:selected?2:1),boxShadow:[BoxShadow(color:Colors.grey.shade100,blurRadius:8,offset:const Offset(0,2))]),child:Row(children:[Icon(icon,size:40,color:selected?AppColors.primary:Colors.grey.shade600),const SizedBox(width:16),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold)),const SizedBox(height:4),Text(description,style:TextStyle(color:Colors.grey.shade600))])),if(selected)const Icon(Icons.check_circle,color:AppColors.primary)]));}
}
