import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/app_strings.dart';
import '../../../core/constants/locale_controller.dart';
import '../../shared/models/care_request.dart';

class AvailableRequestsScreen extends StatefulWidget{const AvailableRequestsScreen({super.key});@override State<AvailableRequestsScreen> createState()=>_AvailableRequestsScreenState();}
class _AvailableRequestsScreenState extends State<AvailableRequestsScreen>{List<CareRequest> _requests=[];List<String> _areas=[];bool _loading=true;String? _error;String t(String k)=>AppStrings.t(k);
 @override void initState(){super.initState();_load();}
 Future<void> _load()async{if(mounted)setState((){_loading=true;_error=null;});try{final uid=FirebaseAuth.instance.currentUser?.uid;if(uid==null)throw Exception('auth');final profile=await FirebaseFirestore.instance.collection('nurseProfiles').doc(uid).get();final values=profile.data()?['preferredGovernorates'];_areas=values is List?values.map((e)=>e.toString()).toList():[];if(_areas.isEmpty){if(mounted)setState((){_requests=[];_loading=false;});return;}final snapshot=await FirebaseFirestore.instance.collection('careRequests').where('status',isEqualTo:'open').where('governorate',whereIn:_areas.take(30).toList()).limit(50).get();final requests=snapshot.docs.map(CareRequest.fromFirestore).toList()..sort((a,b)=>a.startDate.compareTo(b.startDate));if(mounted)setState((){_requests=requests;_loading=false;});}catch(_){if(mounted)setState((){_error=t('available_requests_load_error');_loading=false;});}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(t('nurse_available_requests')),actions:[IconButton(onPressed:_load,tooltip:t('retry'),icon:const Icon(Icons.refresh))]),body:_loading?const Center(child:CircularProgressIndicator()):_buildBody());
 Widget _buildBody(){if(_error!=null)return _state(Icons.error_outline,_error!,t('retry'),_load);if(_areas.isEmpty)return _state(Icons.location_city,t('select_work_area_first'),t('work_settings'),()=>context.push('/nurse/settings'));if(_requests.isEmpty)return _state(Icons.search_off,t('no_open_requests'),t('work_settings'),()=>context.push('/nurse/settings'));return RefreshIndicator(onRefresh:_load,child:ListView.separated(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.all(16),itemCount:_requests.length,separatorBuilder:(_,__)=>const SizedBox(height:10),itemBuilder:(_,i)=>_requestCard(_requests[i])));}
 Widget _requestCard(CareRequest r){final id=r.id.length>6?r.id.substring(0,6):r.id;final locale=LocaleController.instance.isEnglish?'en_US':'ar_EG';return Card(margin:EdgeInsets.zero,child:InkWell(borderRadius:BorderRadius.circular(16),onTap:()=>context.push('/nurse/request-details/${r.id}'),child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[CircleAvatar(backgroundColor:AppColors.primaryLight,child:Icon(Icons.person_outline,color:AppColors.primary)),const SizedBox(width:12),Expanded(child:Text('${t('care_request_number')}$id',style:const TextStyle(fontWeight:FontWeight.bold,fontSize:16))),Icon(LocaleController.instance.isEnglish?Icons.chevron_right:Icons.chevron_left)]),const SizedBox(height:12),Text(_careType(r.careType),style:const TextStyle(fontWeight:FontWeight.w600)),const SizedBox(height:8),Wrap(spacing:12,runSpacing:8,children:[_info(Icons.location_on_outlined,'${_governorate(r.governorate)} - ${r.area}'),_info(Icons.schedule,'${r.shiftHours} ${t('hours_short')}'),_info(Icons.calendar_today_outlined,DateFormat('d/M/yyyy',locale).format(r.startDate))]),if(r.services.isNotEmpty)...[const SizedBox(height:10),Text(r.services.take(3).map(_service).join(' • '),maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:AppColors.textSecondary))]]))));}
 Widget _info(IconData icon,String text)=>Row(mainAxisSize:MainAxisSize.min,children:[Icon(icon,size:16,color:AppColors.textSecondary),const SizedBox(width:4),Text(text,style:const TextStyle(fontSize:12,color:AppColors.textSecondary))]);
 Widget _state(IconData icon,String title,String button,VoidCallback action)=>Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(icon,size:56,color:AppColors.textSecondary),const SizedBox(height:14),Text(title,textAlign:TextAlign.center),const SizedBox(height:16),FilledButton.icon(onPressed:action,icon:Icon(LocaleController.instance.isEnglish?Icons.arrow_forward:Icons.arrow_back),label:Text(button))])));
 String _careType(String v){final k={'elderly':'care_elderly','post_surgery':'care_post_surgery','chronic_disease':'care_chronic','disability':'care_disability','maternity':'care_maternity','general':'care_general'}[v];return k==null?v:t(k);}
 String _service(String v){final k={'متابعة الحالة':'service_followup','إعطاء الأدوية':'service_medication','قياس الضغط':'service_bp','قياس السكر':'service_glucose','تغيير الجروح':'service_wound','مساعدة الحركة':'service_mobility','رعاية كبار السن':'service_elderly','رعاية ما بعد العمليات':'service_post_surgery'}[v];return k==null?v:t(k);}
 String _governorate(String v){const en={'القاهرة':'Cairo','الجيزة':'Giza','الإسكندرية':'Alexandria','القليوبية':'Qalyubia','الدقهلية':'Dakahlia','الشرقية':'Sharqia','الغربية':'Gharbia','المنوفية':'Monufia','البحيرة':'Beheira','كفر الشيخ':'Kafr El Sheikh','دمياط':'Damietta','بورسعيد':'Port Said','الإسماعيلية':'Ismailia','السويس':'Suez','الفيوم':'Fayoum','بني سويف':'Beni Suef','المنيا':'Minya','أسيوط':'Assiut','سوهاج':'Sohag','قنا':'Qena','الأقصر':'Luxor','أسوان':'Aswan','مطروح':'Matrouh','الوادي الجديد':'New Valley','شمال سيناء':'North Sinai','جنوب سيناء':'South Sinai','البحر الأحمر':'Red Sea'};return LocaleController.instance.isEnglish?(en[v]??v):v;}
}
