import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:intl/intl.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/locale_controller.dart';
import '../../shared/models/booking.dart';

class EarningsScreen extends StatefulWidget{const EarningsScreen({super.key});@override State<EarningsScreen> createState()=>_EarningsScreenState();}
class _EarningsScreenState extends State<EarningsScreen>{List<Booking> _transactions=[];bool _loading=true;String? _error;double _total=0,_month=0,_week=0;int _shifts=0;bool get en=>LocaleController.instance.isEnglish;String tx(String ar,String english)=>en?english:ar;
 @override void initState(){super.initState();_load();}
 Future<void> _load()async{if(mounted)setState((){_loading=true;_error=null;});try{final user=FirebaseAuth.instance.currentUser;if(user==null){if(mounted)setState(()=>_error=tx('يرجى تسجيل الدخول','Please log in'));return;}final snapshot=await FirebaseFirestore.instance.collection('bookings').where('nurseId',isEqualTo:user.uid).where('status',isEqualTo:'completed').orderBy('createdAt',descending:true).get();final bookings=snapshot.docs.map(Booking.fromFirestore).toList();final now=DateTime.now(),monthStart=DateTime(now.year,now.month,1),weekStart=now.subtract(Duration(days:now.weekday-1));if(mounted)setState((){_transactions=bookings;_shifts=bookings.length;_total=bookings.fold(0,(sum,b)=>sum+b.totalAmount);_month=bookings.where((b)=>b.createdAt.isAfter(monthStart)).fold(0,(sum,b)=>sum+b.totalAmount);_week=bookings.where((b)=>b.createdAt.isAfter(weekStart)).fold(0,(sum,b)=>sum+b.totalAmount);});}catch(_){if(mounted)setState(()=>_error=tx('حدث خطأ','Something went wrong'));}finally{if(mounted)setState(()=>_loading=false);}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(tx('الأرباح','Earnings'))),body:_loading?const Center(child:CircularProgressIndicator()):_error!=null?Center(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text(_error!,style:const TextStyle(color:AppColors.error)),const SizedBox(height:16),ElevatedButton(onPressed:_load,child:Text(tx('إعادة المحاولة','Retry')))])):Padding(padding:const EdgeInsets.all(16),child:Column(children:[Row(children:[Expanded(child:_summary(tx('الإجمالي','Total'),'${_total.toStringAsFixed(0)} ${tx('ج.م','EGP')}')),const SizedBox(width:12),Expanded(child:_summary(tx('هذا الشهر','This month'),'${_month.toStringAsFixed(0)} ${tx('ج.م','EGP')}'))]),const SizedBox(height:12),Row(children:[Expanded(child:_summary(tx('هذا الأسبوع','This week'),'${_week.toStringAsFixed(0)} ${tx('ج.م','EGP')}')),const SizedBox(width:12),Expanded(child:_summary(tx('عدد الشيفتات','Shifts'),'$_shifts'))]),const SizedBox(height:24),Align(alignment:AlignmentDirectional.centerStart,child:Text(tx('سجل المعاملات','Transactions'),style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold))),const SizedBox(height:8),Expanded(child:_transactions.isEmpty?Center(child:Text(tx('لا توجد معاملات','No transactions'))):ListView.builder(itemCount:_transactions.length,itemBuilder:(context,index){final b=_transactions[index];final id=b.id.length>6?b.id.substring(0,6):b.id;return Card(margin:const EdgeInsets.symmetric(vertical:4),child:ListTile(title:Text('${tx('شيفت','Shift')} #$id'),subtitle:Text(DateFormat.yMMMd(en?'en_US':'ar_EG').format(b.createdAt)),trailing:Text('+${b.totalAmount.toStringAsFixed(0)} ${tx('ج.م','EGP')}',style:const TextStyle(color:AppColors.success,fontWeight:FontWeight.bold)));})))]));
 Widget _summary(String label,String value)=>Card(child:Padding(padding:const EdgeInsets.symmetric(vertical:16,horizontal:8),child:Column(children:[Text(value,style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold)),Text(label,style:const TextStyle(color:AppColors.textSecondary,fontSize:12))]));
}
