import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/app_strings.dart';
import '../../../core/constants/locale_controller.dart';
import '../../../services/auth_service.dart';
import '../../../services/user_service.dart';
import '../../shared/models/app_user.dart';

class NurseMessagesScreen extends StatefulWidget{const NurseMessagesScreen({super.key});@override State<NurseMessagesScreen> createState()=>_NurseMessagesScreenState();}
class _NurseMessagesScreenState extends State<NurseMessagesScreen>{bool _loading=true;String? _error;List<QueryDocumentSnapshot<Map<String,dynamic>>> _chats=[];Map<String,AppUser> _clients={};String t(String k)=>AppStrings.t(k);bool get en=>LocaleController.instance.isEnglish;String tx(String ar,String english)=>en?english:ar;
 @override void initState(){super.initState();_load();}
 Future<void> _load()async{if(mounted)setState((){_loading=true;_error=null;});try{final user=AuthService().currentUser;if(user==null){if(mounted)setState(()=>_error=tx('يرجى تسجيل الدخول','Please log in'));return;}final snapshot=await FirebaseFirestore.instance.collection('chats').where('nurseId',isEqualTo:user.uid).limit(30).get();final chats=[...snapshot.docs]..sort((a,b){final at=a.data()['updatedAt'],bt=b.data()['updatedAt'];if(at is Timestamp&&bt is Timestamp)return bt.compareTo(at);return 0;});final ids=chats.map((d)=>d.data()['clientId']?.toString()??'').where((id)=>id.isNotEmpty);final clients=await UserService().getUsersByIds(ids);if(mounted)setState((){_chats=chats;_clients=clients;});}catch(_){if(mounted)setState(()=>_error=tx('تعذر تحميل الرسائل','Unable to load messages'));}finally{if(mounted)setState(()=>_loading=false);}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(automaticallyImplyLeading:false,title:Text(t('nav_messages')),actions:[IconButton(tooltip:tx('تحديث','Refresh'),onPressed:_load,icon:const Icon(Icons.refresh))]),body:_body());
 Widget _body(){if(_loading)return const Center(child:CircularProgressIndicator());if(_error!=null)return Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.cloud_off_outlined,size:48,color:AppColors.error),const SizedBox(height:12),Text(_error!,textAlign:TextAlign.center),const SizedBox(height:16),FilledButton.icon(onPressed:_load,icon:const Icon(Icons.refresh),label:Text(tx('إعادة المحاولة','Retry')))])));if(_chats.isEmpty)return RefreshIndicator(onRefresh:_load,child:ListView(physics:const AlwaysScrollableScrollPhysics(),children:[const SizedBox(height:120),const Icon(Icons.chat_bubble_outline,size:64),const SizedBox(height:16),Center(child:Text(tx('لا توجد محادثات حتى الآن','No conversations yet'),style:const TextStyle(fontSize:18,fontWeight:FontWeight.w700))),const SizedBox(height:8),Center(child:Padding(padding:const EdgeInsets.symmetric(horizontal:24),child:Text(tx('بعد تأكيد حجز، هتقدر تتواصل مع العميل من هنا.','After a booking is confirmed, you can contact the client here.'),textAlign:TextAlign.center)))]));return RefreshIndicator(onRefresh:_load,child:ListView.separated(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.all(16),itemCount:_chats.length,separatorBuilder:(_,__)=>const SizedBox(height:8),itemBuilder:(context,index){final data=_chats[index].data();final bookingId=data['bookingId'] as String?;final clientId=data['clientId']?.toString();final client=clientId!=null?_clients[clientId]:null;final displayName=client?.name.trim().isNotEmpty==true?client!.name.trim():tx('محادثة','Conversation');final last=data['lastMessage'] as String?;final updated=data['updatedAt'];final date=updated is Timestamp?_formatDate(updated.toDate()):'';return Card(margin:EdgeInsets.zero,child:ListTile(contentPadding:const EdgeInsets.symmetric(horizontal:16,vertical:8),leading:CircleAvatar(backgroundColor:AppColors.primaryLight,backgroundImage:(client?.photoUrl?.isNotEmpty??false)?NetworkImage(client!.photoUrl!):null,child:(client?.photoUrl?.isNotEmpty??false)?null:const Icon(Icons.person_outline)),title:Text(displayName,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text(last?.trim().isNotEmpty==true?last!:tx('ابدأ المحادثة','Start conversation'),maxLines:1,overflow:TextOverflow.ellipsis),trailing:date.isEmpty?Icon(en?Icons.chevron_right:Icons.chevron_left):Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text(date,style:const TextStyle(fontSize:11)),Icon(en?Icons.chevron_right:Icons.chevron_left,size:18)]),onTap:bookingId==null?null:()=>context.push('/nurse/chat/$bookingId')));});}
 String _formatDate(DateTime date){final now=DateTime.now();if(now.year==date.year&&now.month==date.month&&now.day==date.day)return'${date.hour.toString().padLeft(2,'0')}:${date.minute.toString().padLeft(2,'0')}';return'${date.day}/${date.month}/${date.year}';}
}
