import 'dart:typed_data';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:image_picker/image_picker.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/app_strings.dart';
import '../../../core/constants/locale_controller.dart';
import '../../../services/auth_service.dart';
import '../../../services/shared_preferences_service.dart';
import '../../../services/supabase_storage_service.dart';
import '../../../services/user_service.dart';
import '../../shared/models/app_user.dart';

class NurseProfileScreen extends StatefulWidget{const NurseProfileScreen({super.key});@override State<NurseProfileScreen> createState()=>_NurseProfileScreenState();}
class _NurseProfileScreenState extends State<NurseProfileScreen>{AppUser? _user;Map<String,dynamic>? _profile;String? _photoUrl,_error;bool _loading=true,_uploading=false;final _picker=ImagePicker();final _storage=SupabaseStorageService();String t(String k)=>AppStrings.t(k);bool get en=>LocaleController.instance.isEnglish;String tx(String ar,String english)=>en?english:ar;
 @override void initState(){super.initState();_load();}
 Future<void> _load()async{if(mounted)setState((){_loading=true;_error=null;});try{final u=AuthService().currentUser;if(u==null)throw Exception('auth');final results=await Future.wait([UserService().getUser(u.uid),FirebaseFirestore.instance.collection('nurseProfiles').doc(u.uid).get()]);final user=results[0] as AppUser?;final data=(results[1] as DocumentSnapshot<Map<String,dynamic>>).data();if(mounted)setState((){_user=user;_profile=data;_photoUrl=(data?['photoUrl']?.toString().trim().isNotEmpty==true?data!['photoUrl'].toString():user?.photoUrl);_loading=false;});}catch(_){if(mounted)setState(()=>_error=tx('تعذر تحميل الملف الشخصي','Unable to load your profile'));}}
 Future<void> _changePhoto()async{if(_uploading)return;try{final u=FirebaseAuth.instance.currentUser;if(u==null){_message(tx('يرجى تسجيل الدخول أولًا','Please log in first'));return;}final source=await showModalBottomSheet<ImageSource>(context:context,builder:(_)=>SafeArea(child:Wrap(children:[ListTile(leading:const Icon(Icons.camera_alt_outlined),title:Text(tx('التقاط صورة','Take a photo')),onTap:()=>Navigator.pop(context,ImageSource.camera)),ListTile(leading:const Icon(Icons.photo_library_outlined),title:Text(tx('اختيار من المعرض','Choose from gallery')),onTap:()=>Navigator.pop(context,ImageSource.gallery))])));if(source==null)return;final image=await _picker.pickImage(source:source,imageQuality:85,maxWidth:1200,maxHeight:1200);if(image==null)return;final bytes=await image.readAsBytes();if(bytes.isEmpty){_message(tx('الصورة غير صالحة','Invalid image'));return;}setState(()=>_uploading=true);final url=await _storage.uploadNurseProfilePhoto(uid:u.uid,bytes:bytes,contentType:_contentType(image.name));final db=FirebaseFirestore.instance;await db.collection('users').doc(u.uid).set({'photoUrl':url,'updatedAt':FieldValue.serverTimestamp()},SetOptions(merge:true));await db.collection('nurseProfiles').doc(u.uid).set({'photoUrl':url,'updatedAt':FieldValue.serverTimestamp()},SetOptions(merge:true));if(mounted){setState(()=>_photoUrl=url);_message(tx('تم تغيير صورة البروفايل بنجاح','Profile photo updated successfully'));}}catch(_){if(mounted)_message(tx('حدث خطأ أثناء رفع الصورة، حاول مرة أخرى','Unable to upload the photo. Please try again'));}finally{if(mounted)setState(()=>_uploading=false);}}
 String _contentType(String n){final x=n.toLowerCase();if(x.endsWith('.png'))return'image/png';if(x.endsWith('.webp'))return'image/webp';return'image/jpeg';}
 void _message(String s){if(mounted)ScaffoldMessenger.of(context)..hideCurrentSnackBar()..showSnackBar(SnackBar(content:Text(s),behavior:SnackBarBehavior.floating));}
 Future<void> _logout()async{await AuthService().logout();await SharedPreferencesService().clearTempPreferences();if(mounted)context.go('/login');}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(t('my_account'))),body:_loading?const Center(child:CircularProgressIndicator()):_error!=null||_user==null?Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Text(_error??tx('البيانات غير موجودة','No profile data')),const SizedBox(height:12),FilledButton(onPressed:_load,child:Text(t('retry')))])):RefreshIndicator(onRefresh:_load,child:ListView(padding:const EdgeInsets.all(16),physics:const AlwaysScrollableScrollPhysics(),children:[_header(),const SizedBox(height:12),_language(),const SizedBox(height:12),_item(Icons.edit_outlined,t('professional_profile'),()=>context.go('/nurse/professional-profile')),_item(Icons.location_city,t('work_settings'),()=>context.push('/nurse/settings')),_item(Icons.upload_file_outlined,t('documents'),()=>context.push('/nurse/documents')),_item(Icons.verified_outlined,t('verification_status'),()=>context.push('/nurse/verification-status')),_item(Icons.calendar_month_outlined,t('previous_shifts'),()=>context.push('/nurse/previous-shifts')),_item(Icons.payments_outlined,t('nurse_earnings'),()=>context.push('/nurse/earnings')),_item(Icons.stars_outlined,'Nurse Pro',()=>context.push('/nurse/nurse-pro')),_item(Icons.star_outline,t('reviews'),()=>context.push('/nurse/reviews')),_item(Icons.logout,t('logout'),_logout,destructive:true)]));
 Widget _language()=>Card(child:ListTile(leading:const Icon(Icons.language,color:AppColors.primary),title:Text(t('language')),trailing:Row(mainAxisSize:MainAxisSize.min,children:[Text(en?t('english'):t('arabic')),Switch(value:en,onChanged:(v)=>LocaleController.instance.setLocale(v?const Locale('en','US'):const Locale('ar','EG')))]));
 Widget _header(){final name=_user!.name.trim();return Card(child:Padding(padding:const EdgeInsets.all(20),child:Column(children:[Stack(clipBehavior:Clip.none,children:[GestureDetector(onTap:_uploading?null:_changePhoto,child:CircleAvatar(radius:52,backgroundColor:AppColors.primaryLight,backgroundImage:_photoUrl?.isNotEmpty==true?NetworkImage(_photoUrl!):null,child:_photoUrl?.isNotEmpty==true?null:Text(name.isNotEmpty?name[0]:'?',style:const TextStyle(fontSize:38,color:AppColors.primary,fontWeight:FontWeight.bold)))),Positioned(bottom:0,end:-2,child(Material(color:AppColors.primary,shape:const CircleBorder(),child:InkWell(customBorder:const CircleBorder(),onTap:_uploading?null:_changePhoto,child:Padding(padding:const EdgeInsets.all(9),child:_uploading?const SizedBox(width:20,height:20,child:CircularProgressIndicator(strokeWidth:2,color:Colors.white)):const Icon(Icons.camera_alt,color:Colors.white,size:20))))))]),const SizedBox(height:8),Text(tx('اضغط على الصورة لتغييرها','Tap the photo to change it'),style:const TextStyle(color:AppColors.textSecondary,fontSize:12)),const SizedBox(height:8),Text(name,style:Theme.of(context).textTheme.headlineSmall,textAlign:TextAlign.center),if(_user!.isVerified)Padding(padding:const EdgeInsets.only(top:6),child:Row(mainAxisAlignment:MainAxisAlignment.center,children:[const Icon(Icons.verified,color:AppColors.success,size:18),const SizedBox(width:5),Text(tx('حساب موثق','Verified account'),style:const TextStyle(color:AppColors.success,fontWeight:FontWeight.w600))])),const SizedBox(height:6),Text(_user!.phone,style:const TextStyle(color:AppColors.textSecondary))])));}
 Widget _item(IconData icon,String title,VoidCallback tap,{bool destructive=false})=>Card(margin:const EdgeInsets.only(bottom:8),child:ListTile(leading:Icon(icon,color:destructive?AppColors.error:AppColors.primary),title:Text(title,style:TextStyle(color:destructive?AppColors.error:null,fontWeight:FontWeight.w500)),trailing:Icon(en?Icons.arrow_forward_ios:Icons.arrow_back_ios,size:16),onTap:tap));
}
