import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/locale_controller.dart';
import '../../../services/review_service.dart';
import '../../shared/models/review.dart';

class NurseReviewsScreen extends StatefulWidget{const NurseReviewsScreen({super.key});@override State<NurseReviewsScreen> createState()=>_NurseReviewsScreenState();}
class _NurseReviewsScreenState extends State<NurseReviewsScreen>{final _service=ReviewService();List<Review> _reviews=[];bool _loading=true;String? _error;bool get en=>LocaleController.instance.isEnglish;String tx(String ar,String english)=>en?english:ar;
 @override void initState(){super.initState();_load();}
 Future<void> _load()async{if(mounted)setState((){_loading=true;_error=null;});try{final user=FirebaseAuth.instance.currentUser;if(user==null)throw StateError('auth');final reviews=await _service.getNurseReviews(user.uid,limit:100);if(mounted)setState(()=>_reviews=reviews);}catch(_){if(mounted)setState(()=>_error=tx('تعذر تحميل التقييمات. حاول مرة أخرى.','Unable to load reviews. Please try again.'));}finally{if(mounted)setState(()=>_loading=false);}}
 double get _average=>_reviews.isEmpty?0:_reviews.fold<int>(0,(sum,r)=>sum+r.rating)/_reviews.length;Map<int,int> get _distribution{final r=<int,int>{1:0,2:0,3:0,4:0,5:0};for(final x in _reviews)r[x.rating]=(r[x.rating]??0)+1;return r;}
 @override Widget build(BuildContext context){if(_loading)return const Scaffold(body:Center(child:CircularProgressIndicator()));if(_error!=null)return Scaffold(appBar:AppBar(title:Text(tx('تقييماتي','My reviews'))),body:Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Text(_error!,style:const TextStyle(color:AppColors.error)),const SizedBox(height:14),FilledButton.icon(onPressed:_load,icon:const Icon(Icons.refresh),label:Text(tx('إعادة المحاولة','Retry')))])));final d=_distribution;return Scaffold(appBar:AppBar(title:Text(tx('تقييماتي','My reviews')),automaticallyImplyLeading:false,actions:[IconButton(onPressed:_load,tooltip:tx('تحديث','Refresh'),icon:const Icon(Icons.refresh))]),body:RefreshIndicator(onRefresh:_load,child:ListView(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.all(16),children:[Card(child:Padding(padding:const EdgeInsets.all(18),child:Row(children:[const Icon(Icons.star,size:44,color:Colors.amber),const SizedBox(width:12),Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(_average.toStringAsFixed(1),style:const TextStyle(fontSize:30,fontWeight:FontWeight.bold)),Text('${_reviews.length} ${tx('تقييم','reviews')}',style:const TextStyle(color:AppColors.textSecondary))])])),const SizedBox(height:12),Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(children:List.generate(5,(i){final star=5-i;final count=d[star]??0;final value=_reviews.isEmpty?0.0:count/_reviews.length;return Padding(padding:const EdgeInsets.symmetric(vertical:4),child:Row(children:[SizedBox(width:42,child:Text('$star ⭐')),Expanded(child:LinearProgressIndicator(value:value,minHeight:8,backgroundColor:Colors.grey.shade200,color:Colors.amber)),SizedBox(width:35,child:Text('$count',textAlign:TextAlign.end))]));}))),const SizedBox(height:18),Text(tx('آراء العملاء','Client reviews'),style:const TextStyle(fontSize:19,fontWeight:FontWeight.bold)),const SizedBox(height:8),if(_reviews.isEmpty)Padding(padding:const EdgeInsets.only(top:60),child:Center(child:Text(tx('لسه مفيش تقييمات','No reviews yet'))))else ..._reviews.map(_card)]));}
 Widget _card(Review review)=>Card(margin:const EdgeInsets.only(bottom:10),child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[...List.generate(5,(i)=>Icon(i<review.rating?Icons.star:Icons.star_border,color:Colors.amber,size:18)),const Spacer(),Text('${review.createdAt.day}/${review.createdAt.month}/${review.createdAt.year}',style:const TextStyle(fontSize:11,color:AppColors.textSecondary))]),if(review.comment?.trim().isNotEmpty==true)...[const SizedBox(height:8),Text(review.comment!)]])));
}
