import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/locale_controller.dart';

class NurseProScreen extends StatefulWidget{const NurseProScreen({super.key});@override State<NurseProScreen> createState()=>_NurseProScreenState();}
class _NurseProScreenState extends State<NurseProScreen>{bool _loading=true;String? _error;int _completed=0;double _rating=0,_progress=0;String _level='Bronze';int _nextTarget=20;bool get en=>LocaleController.instance.isEnglish;String tx(String ar,String english)=>en?english:ar;final Map<String,LevelData> _levels={
 'Bronze':LevelData('🟢 ${'Bronze'}',0,0,['الطلبات العادية']),
 'Silver':LevelData('🔵 ${'Silver'}',20,4.5,['أولوية بسيطة في الطلبات']),
 'Gold':LevelData('🟣 ${'Gold'}',50,4.7,['طلبات أفضل','عمولة أقل']),
 'Platinum':LevelData('🟡 ${'Platinum'}',100,4.9,['أولوية قصوى','عمولة منخفضة'])};
 @override void initState(){super.initState();_load();}
 Future<void> _load()async{if(mounted)setState((){_loading=true;_error=null;});try{final user=FirebaseAuth.instance.currentUser;if(user==null)throw StateError('auth');final shifts=await FirebaseFirestore.instance.collection('bookings').where('nurseId',isEqualTo:user.uid).where('status',isEqualTo:'completed').get();final reviews=await FirebaseFirestore.instance.collection('reviews').where('nurseId',isEqualTo:user.uid).get();_completed=shifts.docs.length;if(reviews.docs.isNotEmpty){final sum=reviews.docs.fold<double>(0,(s,d)=>s+((d.data()['rating'] as num?)?.toDouble()??0));_rating=sum/reviews.docs.length;}_level='Bronze';for(final e in _levels.entries){if(_completed>=e.value.minShifts&&_rating>=e.value.minRating)_level=e.key;}final keys=_levels.keys.toList(),idx=keys.indexOf(_level);if(idx<keys.length-1){final next=_levels[keys[idx+1]]!,current=_levels[_level]!,range=next.minShifts-current.minShifts;_nextTarget=next.minShifts;_progress=((_completed-current.minShifts)/range).clamp(0.0,1.0);}else{_progress=1;_nextTarget=_completed;}if(mounted)setState((){});}catch(_){if(mounted)setState(()=>_error=tx('حدث خطأ','Something went wrong'));}finally{if(mounted)setState(()=>_loading=false);}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text('Nurse Pro')),body:_loading?const Center(child:CircularProgressIndicator()):_error!=null?Center(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text(_error!,style:const TextStyle(color:AppColors.error)),const SizedBox(height:16),ElevatedButton(onPressed:_load,child:Text(tx('إعادة المحاولة','Retry')))])):Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Center(child:Column(children:[Text(_levelLabel(_level),style:const TextStyle(fontSize:32,fontWeight:FontWeight.bold)),const SizedBox(height:4),Text('${_completed} ${tx('شيفت مكتمل','completed shifts')} • ${_rating.toStringAsFixed(1)} ⭐',style:const TextStyle(color:AppColors.textSecondary))])),const SizedBox(height:16),if(_level!='Platinum')... [Text(tx('التقدم إلى المستوى التالي','Progress to next level'),style:const TextStyle(fontWeight:FontWeight.bold)),const SizedBox(height:4),LinearProgressIndicator(value:_progress,minHeight:12),const SizedBox(height:4),Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text('$_completed ${tx('شيفت','shifts')}',style:const TextStyle(fontSize:12)),Text('$_nextTarget ${tx('شيفت','shifts')}',style:const TextStyle(fontSize:12))])],const SizedBox(height:24),Text(tx('المزايا','Benefits'),style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold)),const SizedBox(height:8),..._levels.entries.map((e){final active=_levels.keys.toList().indexOf(e.key)<=_levels.keys.toList().indexOf(_level);return Card(margin:const EdgeInsets.symmetric(vertical:4),child:ListTile(leading:Icon(active?Icons.check_circle:Icons.lock,color:active?AppColors.success:Colors.grey),title:Text(_levelLabel(e.key)),subtitle:Text(e.value.benefits.map(_benefit).join(' • '))));})]));
 String _levelLabel(String s)=>switch(s){'Bronze'=>tx('🟢 برونز','🟢 Bronze'),'Silver'=>tx('🔵 فضي','🔵 Silver'),'Gold'=>tx('🟣 ذهبي','🟣 Gold'),'Platinum'=>tx('🟡 بلاتينيوم','🟡 Platinum'),_=>s};String _benefit(String s)=>switch(s){'الطلبات العادية'=>tx(s,'Standard requests'),'أولوية بسيطة في الطلبات'=>tx(s,'Basic request priority'),'طلبات أفضل'=>tx(s,'Better requests'),'عمولة أقل'=>tx(s,'Lower commission'),'أولوية قصوى'=>tx(s,'Top priority'),'عمولة منخفضة'=>tx(s,'Low commission'),_=>s};}
class LevelData{final String label;final int minShifts;final double minRating;final List<String> benefits;LevelData(this.label,this.minShifts,this.minRating,this.benefits);}
