import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/locale_controller.dart';

class NurseProfessionalProfileScreen extends StatefulWidget{const NurseProfessionalProfileScreen({super.key});@override State<NurseProfessionalProfileScreen> createState()=>_NurseProfessionalProfileScreenState();}
class _NurseProfessionalProfileScreenState extends State<NurseProfessionalProfileScreen>{bool _loading=true,_saving=false;String? _error;final _formKey=GlobalKey<FormState>();final _experience=TextEditingController(),_price=TextEditingController(),_bio=TextEditingController();String? _specialization;List<String> _services=[];bool get en=>LocaleController.instance.isEnglish;String tx(String ar,String english)=>en?english:ar;final _specializations=['تمريض عام','تمريض طوارئ','تمريض عناية مركزة','تمريض أطفال','تمريض كبار السن','تمريض منازل','تمريض عمليات'];final _allServices=['متابعة الحالة','إعطاء الأدوية','قياس الضغط','قياس السكر','تغيير الجروح','مساعدة الحركة','رعاية كبار السن','رعاية ما بعد العمليات','تمريض الأطفال','العناية بالتنفس'];
 @override void initState(){super.initState();_load();}@override void dispose(){_experience.dispose();_price.dispose();_bio.dispose();super.dispose();}
 Future<void> _load()async{if(mounted)setState(()=>_loading=true);try{final user=FirebaseAuth.instance.currentUser;if(user==null)throw Exception('auth');final doc=await FirebaseFirestore.instance.collection('nurseProfiles').doc(user.uid).get();final data=doc.data()??{};if(mounted)setState((){_experience.text='${data['experienceYears']??0}';_price.text='${data['expectedPrice']??0}';_bio.text='${data['bio']??''}';_specialization=data['specialization']??'تمريض عام';_services=List<String>.from(data['services']??[]);});}catch(_){if(mounted)setState(()=>_error=tx('حدث خطأ في تحميل البيانات','Unable to load your data'));}finally{if(mounted)setState(()=>_loading=false);}}
 Future<void> _save()async{if(!_formKey.currentState!.validate())return;final user=FirebaseAuth.instance.currentUser;if(user==null){setState(()=>_error=tx('يرجى تسجيل الدخول','Please log in'));return;}setState(()=>_saving=true);try{await FirebaseFirestore.instance.collection('nurseProfiles').doc(user.uid).set({'uid':user.uid,'specialization':_specialization,'experienceYears':int.tryParse(_experience.text.trim())??0,'services':_services,'expectedPrice':double.tryParse(_price.text.trim())??0,'bio':_bio.text.trim(),'updatedAt':FieldValue.serverTimestamp()},SetOptions(merge:true));if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(tx('تم حفظ البيانات بنجاح','Profile saved successfully'))));}catch(_){if(mounted)setState(()=>_error=tx('حدث خطأ في الحفظ','Unable to save changes'));}finally{if(mounted)setState(()=>_saving=false);}}
 @override Widget build(BuildContext context)=>Scaffold(backgroundColor:AppColors.background,appBar:AppBar(title:Text(tx('الملف المهني','Professional profile'))),body:_loading?const Center(child:CircularProgressIndicator()):_error!=null&&_specialization==null?Center(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text(_error!,style:const TextStyle(color:AppColors.error)),const SizedBox(height:16),ElevatedButton(onPressed:_load,child:Text(tx('إعادة المحاولة','Retry')))])):Padding(padding:const EdgeInsets.all(16),child:Form(key:_formKey,child:SingleChildScrollView(child:Column(children:[DropdownButtonFormField<String>(initialValue:_specialization,decoration:InputDecoration(labelText:tx('التخصص','Specialization'),prefixIcon:const Icon(Icons.medical_information)),items:_specializations.map((s)=>DropdownMenuItem(value:s,child:Text(_specializationLabel(s)))).toList(),onChanged:(v)=>setState(()=>_specialization=v)),const SizedBox(height:12),TextFormField(controller:_experience,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:tx('سنوات الخبرة','Years of experience'),prefixIcon:const Icon(Icons.timeline)),validator:(v)=>v==null||v.trim().isEmpty?tx('الخبرة مطلوبة','Experience is required'):null),const SizedBox(height:12),TextFormField(controller:_price,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:InputDecoration(labelText:tx('السعر المتوقع (ج.م/ساعة)','Expected price (EGP/hour)'),prefixIcon:const Icon(Icons.money)),validator:(v)=>v==null||double.tryParse(v.trim())==null?tx('السعر مطلوب','Enter a valid price'):null),const SizedBox(height:12),TextFormField(controller:_bio,minLines:3,maxLines:5,decoration:InputDecoration(labelText:tx('نبذة عني (تظهر للعميل)','About me (shown to clients)'),alignLabelWithHint:true,prefixIcon:const Padding(padding:EdgeInsets.only(bottom:48),child:Icon(Icons.info_outline))),const SizedBox(height:12),Align(alignment:AlignmentDirectional.centerStart,child:Text(tx('الخدمات','Services'),style:const TextStyle(fontWeight:FontWeight.bold))),const SizedBox(height:6),Wrap(spacing:8,runSpacing:8,children:_allServices.map((s)=>FilterChip(label:Text(_serviceLabel(s)),selected:_services.contains(s),onSelected:(v)=>setState(()=>v?_services.add(s):_services.remove(s)))).toList()),const SizedBox(height:16),if(_error!=null)Text(_error!,style:const TextStyle(color:AppColors.error),textAlign:TextAlign.center),const SizedBox(height:16),SizedBox(width:double.infinity,height:50,child:ElevatedButton(onPressed:_saving?null:_save,child:_saving?const SizedBox(width:20,height:20,child:CircularProgressIndicator(color:Colors.white,strokeWidth:2)):Text(tx('حفظ التغييرات','Save changes'))))]))));
 String _specializationLabel(String s){const m={'تمريض عام':'General nursing','تمريض طوارئ':'Emergency nursing','تمريض عناية مركزة':'Critical care nursing','تمريض أطفال':'Pediatric nursing','تمريض كبار السن':'Elderly care nursing','تمريض منازل':'Home nursing','تمريض عمليات':'Operating room nursing'};return en?(m[s]??s):s;}
 String _serviceLabel(String s){const m={'متابعة الحالة':'service_followup','إعطاء الأدوية':'service_medication','قياس الضغط':'service_bp','قياس السكر':'service_glucose','تغيير الجروح':'service_wound','مساعدة الحركة':'service_mobility','رعاية كبار السن':'service_elderly','رعاية ما بعد العمليات':'service_post_surgery'};return en&&m[s]!=null?({'service_followup':'Patient monitoring','service_medication':'Medication administration','service_bp':'Blood pressure check','service_glucose':'Blood glucose check','service_wound':'Wound dressing','service_mobility':'Mobility assistance','service_elderly':'Elderly care','service_post_surgery':'Post-surgery care'}[m[s]]??s):s;}
}
