import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:intl/intl.dart';
import 'package:go_router/go_router.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/locale_controller.dart';
import '../../shared/models/booking.dart';

class NurseShiftsScreen extends StatefulWidget{const NurseShiftsScreen({super.key});@override State<NurseShiftsScreen> createState()=>_NurseShiftsScreenState();}
class _NurseShiftsScreenState extends State<NurseShiftsScreen> with SingleTickerProviderStateMixin{late final TabController _tabs;List<Booking> _upcoming=[],_past=[];bool _loading=true;String? _error;bool get en=>LocaleController.instance.isEnglish;String tx(String ar,String english)=>en?english:ar;
 @override void initState(){super.initState();_tabs=TabController(length:2,vsync:this);_load();}@override void dispose(){_tabs.dispose();super.dispose();}
 Future<void> _load()async{if(mounted)setState((){_loading=true;_error=null;});try{final user=FirebaseAuth.instance.currentUser;if(user==null)throw StateError('auth');final s=await FirebaseFirestore.instance.collection('bookings').where('nurseId',isEqualTo:user.uid).orderBy('shiftStart').get();final all=s.docs.map(Booking.fromFirestore).toList();final now=DateTime.now();if(mounted)setState((){_upcoming=all.where((b)=>b.status=='confirmed'||b.status=='in_progress'||(b.status=='pending_payment'&&b.shiftStart.isAfter(now.subtract(const Duration(hours:1))))).toList();_past=all.where((b)=>b.status=='completed'||b.status=='cancelled'||b.status=='disputed'||(b.status=='pending_payment'&&b.shiftStart.isBefore(now.subtract(const Duration(hours:1))))).toList();});}catch(_){if(mounted)setState(()=>_error=tx('حدث خطأ في تحميل الشيفتات','Unable to load shifts'));}finally{if(mounted)setState(()=>_loading=false);}}
 String _remaining(Booking b){final d=b.shiftStart.difference(DateTime.now());if(d.isNegative)return'${tx('بدأت منذ','Started')} ${_duration(d.abs())}';return'${tx('تبدأ بعد','Starts in')} ${_duration(d)}';}String _duration(Duration d){if(d.inDays>0)return'${d.inDays} ${tx('يوم','days')}';if(d.inHours>0)return'${d.inHours} ${tx('ساعة','hours')}';if(d.inMinutes>0)return'${d.inMinutes} ${tx('دقيقة','minutes')}';return tx('أقل من دقيقة','Less than a minute');}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(tx('الشيفتات','Shifts')),actions:[IconButton(onPressed:_load,tooltip:tx('تحديث','Refresh'),icon:const Icon(Icons.refresh))],bottom:TabBar(controller:_tabs,tabs:[Tab(icon:const Icon(Icons.event_available),text:tx('القادمة','Upcoming')),Tab(icon:const Icon(Icons.history),text:tx('السابقة','Previous'))])),body:_loading?const Center(child:CircularProgressIndicator()):_error!=null?Center(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text(_error!,style:const TextStyle(color:AppColors.error)),const SizedBox(height:16),ElevatedButton(onPressed:_load,child:Text(tx('إعادة المحاولة','Retry')))])):TabBarView(controller:_tabs,children:[_list(_upcoming,true),_list(_past,false)]));
 Widget _list(List<Booking> shifts,bool upcoming){if(shifts.isEmpty)return Center(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(upcoming?Icons.event_busy:Icons.history,size:60,color:Colors.grey),const SizedBox(height:16),Text(upcoming?tx('لا توجد شيفتات قادمة','No upcoming shifts'):tx('لا توجد شيفتات سابقة','No previous shifts')),const SizedBox(height:8),Text(upcoming?tx('ستظهر هنا الشيفتات المؤكدة والقادمة','Confirmed upcoming shifts will appear here'):tx('ستظهر هنا الشيفتات المكتملة والملغاة','Completed and cancelled shifts will appear here'))]));final locale=en?'en_US':'ar_EG';return ListView.builder(padding:const EdgeInsets.all(12),itemCount:shifts.length,itemBuilder:(context,i){final b=shifts[i];final id=b.id.length>6?b.id.substring(0,6):b.id;return Card(margin:const EdgeInsets.only(bottom:12),child:InkWell(onTap:()=>context.go('/nurse/current-shift?bookingId=${b.id}'),child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Container(width:8,height:8,decoration:BoxDecoration(color:upcoming?Colors.green:Colors.grey,shape:BoxShape.circle)),const SizedBox(width:8),Expanded(child:Text('${tx('شيفت','Shift')} #$id',style:const TextStyle(fontSize:16,fontWeight:FontWeight.bold))),Text(_status(b.status),style:TextStyle(color:_statusColor(b.status),fontWeight:FontWeight.bold))]),const SizedBox(height:12),Text(DateFormat('EEEE، d MMM yyyy',locale).format(b.shiftStart)),const SizedBox(height:6),Text('${DateFormat.jm(locale).format(b.shiftStart)} - ${DateFormat.jm(locale).format(b.shiftEnd)}'),const SizedBox(height:6),Text('${b.shiftHours} ${tx('ساعة','hours')}'),const Divider(height:24),Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text('${b.totalAmount.toStringAsFixed(0)} ${tx('ج.م','EGP')}',style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold,color:AppColors.primary)),if(upcoming)Text(_remaining(b),style:const TextStyle(fontSize:12,color:AppColors.primary)),Icon(en?Icons.arrow_forward_ios:Icons.arrow_back_ios,size:15)])]))));});}
 String _status(String s)=>switch(s){'pending_payment'=>tx('انتظار الدفع','Awaiting payment'),'confirmed'=>tx('مؤكد','Confirmed'),'in_progress'=>tx('جاري','In progress'),'completed'=>tx('مكتمل','Completed'),'cancelled'=>tx('ملغي','Cancelled'),'disputed'=>tx('نزاع','Disputed'),_=>s};Color _statusColor(String s)=>switch(s){'pending_payment'=>Colors.orange,'confirmed'=>Colors.blue,'in_progress'=>Colors.green,'completed'=>Colors.teal,'cancelled'=>Colors.red,'disputed'=>Colors.purple,_=>Colors.grey};
}
