import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/locale_controller.dart';

class NurseDocumentsScreen extends StatefulWidget{const NurseDocumentsScreen({super.key});@override State<NurseDocumentsScreen> createState()=>_NurseDocumentsScreenState();}
class _NurseDocumentsScreenState extends State<NurseDocumentsScreen>{static const requiredIds={'id_card','qualification'};final _picker=ImagePicker();final _types=const[DocumentType(id:'id_card',label:'بطاقة الهوية',required:true,icon:Icons.credit_card_outlined),DocumentType(id:'qualification',label:'المؤهل الدراسي',required:true,icon:Icons.school_outlined),DocumentType(id:'license',label:'ترخيص مزاولة المهنة',required:false,icon:Icons.verified_outlined)];bool _loading=true,_uploading=false;String? _error;Map<String,String> _documents={};String _status='not_submitted';String? _reason;bool get en=>LocaleController.instance.isEnglish;String tx(String ar,String english)=>en?english:ar;
 @override void initState(){super.initState();_load();}
 Future<void> _load()async{if(mounted)setState((){_loading=true;_error=null;});try{final uid=FirebaseAuth.instance.currentUser?.uid;if(uid==null)throw StateError('auth');final doc=await FirebaseFirestore.instance.collection('nurseDocuments').doc(uid).get();if(!mounted)return;if(doc.exists){final data=doc.data()??{};final raw=data['documents'];_documents=raw is Map?raw.map((k,v)=>MapEntry(k.toString(),v.toString())):{};_status=data['verificationStatus']?.toString()??'not_submitted';_reason=data['rejectionReason']?.toString();}}catch(_){if(mounted)setState(()=>_error=tx('تعذر تحميل المستندات','Unable to load documents'));}finally{if(mounted)setState(()=>_loading=false);}}
 Future<void> _upload(DocumentType type)async{if(_uploading)return;try{final image=await _picker.pickImage(source:ImageSource.gallery,imageQuality:82,maxWidth:1800);if(image==null)return;final uid=FirebaseAuth.instance.currentUser?.uid;if(uid==null)throw StateError('auth');setState((){_uploading=true;_error=null;});final ref=FirebaseStorage.instance.ref().child('nurse_documents').child(uid).child('${type.id}.jpg');await ref.putFile(File(image.path),SettableMetadata(contentType:'image/jpeg'));final url=await ref.getDownloadURL();final updated=Map<String,String>.from(_documents)..[type.id]=url;await FirebaseFirestore.instance.collection('nurseDocuments').doc(uid).set({'uid':uid,'documents':updated,'verificationStatus':_status=='approved'?'approved':'not_submitted','updatedAt':FieldValue.serverTimestamp()},SetOptions(merge:true));if(!mounted)return;setState((){_documents=updated;if(_status!='approved')_status='not_submitted';_reason=null;});_message(tx('تم رفع ${type.label} بنجاح', '${type.englishLabel} uploaded successfully'));}catch(_){if(mounted)setState(()=>_error=tx('تعذر رفع المستند. تأكد من اختيار صورة واضحة وحاول مرة أخرى.','Unable to upload the document. Choose a clear image and try again.'));}finally{if(mounted)setState(()=>_uploading=false);}}
 Future<void> _submit()async{final uid=FirebaseAuth.instance.currentUser?.uid;if(uid==null)return;final missing=requiredIds.where((id)=>!_documents.containsKey(id));if(missing.isNotEmpty){_message(tx('ارفع البطاقة والمؤهل الدراسي أولاً','Upload the ID card and qualification first'));return;}setState(()=>_uploading=true);try{await FirebaseFirestore.instance.collection('nurseDocuments').doc(uid).set({'uid':uid,'documents':_documents,'verificationStatus':'pending','submittedAt':FieldValue.serverTimestamp(),'updatedAt':FieldValue.serverTimestamp()},SetOptions(merge:true));if(!mounted)return;setState((){_status='pending';_reason=null;});_message(tx('تم إرسال المستندات للمراجعة','Documents submitted for review'));}catch(_){if(mounted)setState(()=>_error=tx('تعذر إرسال المستندات للمراجعة','Unable to submit documents for review'));}finally{if(mounted)setState(()=>_uploading=false);}}
 void _message(String s){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));}
 String _statusLabel(String s)=>switch(s){'pending'=>tx('قيد المراجعة','Under review'),'approved'=>tx('تم التحقق','Verified'),'rejected'=>tx('مرفوض ويحتاج تعديل','Rejected - needs changes'),_=>tx('لم يتم الإرسال للمراجعة','Not submitted for review')};
 Color _statusColor(String s)=>switch(s){'pending'=>Colors.orange,'approved'=>Colors.green,'rejected'=>Colors.red,_=>Colors.grey};
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(tx('توثيق الحساب','Account verification'))),body:_loading?const Center(child:CircularProgressIndicator()):_error!=null&&_documents.isEmpty?_errorState():ListView(padding:const EdgeInsets.fromLTRB(16,16,16,32),children:[_statusCard(),const SizedBox(height:16),Text(tx('المستندات المطلوبة','Required documents'),style:const TextStyle(fontSize:19,fontWeight:FontWeight.bold)),const SizedBox(height:6),Text(tx('البطاقة والمؤهل الدراسي مطلوبان. ترخيص مزاولة المهنة اختياري إذا كان متاحًا.','ID and qualification are required. A professional license is optional if available.'),style:const TextStyle(color:AppColors.textSecondary)),const SizedBox(height:14),..._types.map(_documentCard),if(_error!=null)...[const SizedBox(height:8),Text(_error!,textAlign:TextAlign.center,style:const TextStyle(color:AppColors.error))],const SizedBox(height:14),SizedBox(height:52,child:FilledButton.icon(onPressed:_uploading||_status=='pending'||_status=='approved'?null:_submit,icon:_uploading?const SizedBox(width:20,height:20,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.send_outlined),label:Text(_status=='pending'?tx('قيد المراجعة','Under review'):_status=='approved'?tx('تم التحقق','Verified'):tx('إرسال للمراجعة','Submit for review'))))]);
 Widget _errorState()=>Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.cloud_off_outlined,size:56),const SizedBox(height:12),Text(_error??tx('حدث خطأ','Something went wrong')),const SizedBox(height:16),FilledButton.icon(onPressed:_load,icon:const Icon(Icons.refresh),label:Text(tx('إعادة المحاولة','Retry')))]));
 Widget _statusCard(){final color=_statusColor(_status);return Card(child:Padding(padding:const EdgeInsets.all(16),child:Row(children:[Icon(_status=='approved'?Icons.check_circle:Icons.info_outline,color:color),const SizedBox(width:10),Expanded(child:Text('${tx('حالة التوثيق:','Verification status:')} ${_statusLabel(_status)}',style:TextStyle(fontWeight:FontWeight.bold,color:color)))])));}
 Widget _documentCard(DocumentType type){final uploaded=_documents.containsKey(type.id);return Card(margin:const EdgeInsets.only(bottom:10),child:ListTile(leading:Icon(type.icon,color:uploaded?AppColors.success:AppColors.primary),title:Text(en?type.englishLabel:type.label),subtitle:Text(type.required?tx('مطلوب','Required'):tx('اختياري','Optional')),trailing:uploaded?IconButton(icon:const Icon(Icons.visibility_outlined),onPressed:()=>_preview(_documents[type.id]!)):FilledButton.tonal(onPressed:_uploading?null:()=>_upload(type),child:Text(tx('رفع','Upload')))));}
 void _preview(String url)=>showDialog<void>(context:context,builder:(_)=>Dialog(child:InteractiveViewer(child:Image.network(url,fit:BoxFit.contain,errorBuilder:(_,__,___)=>Padding(padding:const EdgeInsets.all(32),child:Text(tx('تعذر عرض الصورة','Unable to display image')))))));
}
class DocumentType{final String id,label;final bool required;final IconData icon;const DocumentType({required this.id,required this.label,required this.required,required this.icon});String get englishLabel=>switch(id){'id_card'=>'ID card','qualification'=>'Educational qualification','license'=>'Professional license',_=>label};}
