import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/app_strings.dart';
import '../../../core/constants/locale_controller.dart';
import '../../../services/user_service.dart';
import '../../shared/models/care_request.dart';
import '../../shared/models/booking.dart';

class NurseHomeScreen extends StatefulWidget { const NurseHomeScreen({super.key}); @override State<NurseHomeScreen> createState()=>_NurseHomeScreenState(); }
class _NurseHomeScreenState extends State<NurseHomeScreen>{String _userName='';bool _isLoading=true,_isVerified=false;int _pendingRequestsCount=0,_todayShiftsCount=0;double _totalEarnings=0,_averageRating=0;List<CareRequest> _availableRequests=[];String t(String k)=>AppStrings.t(k);
 @override void initState(){super.initState();_loadData();}
 Future<void> _loadData()async{if(mounted)setState(()=>_isLoading=true);final user=FirebaseAuth.instance.currentUser;if(user==null){if(mounted)setState(()=>_isLoading=false);return;}try{final appUser=await UserService().getUser(user.uid);if(appUser!=null&&mounted)setState((){_userName=appUser.name.trim().isNotEmpty?appUser.name.trim():t('nurse');_isVerified=appUser.isVerified;});}catch(e){debugPrint('nurse_home user: $e');}try{final s=await FirebaseFirestore.instance.collection('careRequests').where('status',isEqualTo:'open').limit(20).get();final requests=s.docs.map(CareRequest.fromFirestore).toList();if(mounted)setState((){_availableRequests=requests;_pendingRequestsCount=requests.length;});}catch(e){debugPrint('nurse_home requests: $e');}try{final now=DateTime.now();final start=DateTime(now.year,now.month,now.day);final end=start.add(const Duration(days:1));final s=await FirebaseFirestore.instance.collection('bookings').where('nurseId',isEqualTo:user.uid).where('status',whereIn:['confirmed','in_progress']).where('shiftStart',isGreaterThanOrEqualTo:start).where('shiftStart',isLessThan:end).get();if(mounted)setState(()=>_todayShiftsCount=s.docs.length);}catch(e){debugPrint('nurse_home shifts: $e');}try{final s=await FirebaseFirestore.instance.collection('bookings').where('nurseId',isEqualTo:user.uid).where('status',isEqualTo:'completed').get();final bs=s.docs.map(Booking.fromFirestore);if(mounted)setState(()=>_totalEarnings=bs.fold(0.0,(sum,b)=>sum+b.totalAmount));}catch(e){debugPrint('nurse_home earnings: $e');}try{final s=await FirebaseFirestore.instance.collection('reviews').where('nurseId',isEqualTo:user.uid).get();if(s.docs.isNotEmpty&&mounted){final sum=s.docs.fold<double>(0,(v,d)=>v+((d.data()['rating']??0)as num).toDouble());setState(()=>_averageRating=sum/s.docs.length);}}catch(e){debugPrint('nurse_home reviews: $e');}if(mounted)setState(()=>_isLoading=false);}
 @override Widget build(BuildContext context)=>Scaffold(backgroundColor:AppColors.background,appBar:AppBar(title:Text(t('nurse_home_title')),automaticallyImplyLeading:false),body:_isLoading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:_loadData,child:ListView(padding:const EdgeInsets.all(16),children:[Text('${t('welcome')}, $_userName 🩺',style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:12),if(!_isVerified)...[_verificationCard(),const SizedBox(height:16)],Row(children:[Expanded(child:_stat(t('nurse_new_requests'),'$_pendingRequestsCount',Icons.request_page)),const SizedBox(width:12),Expanded(child:_stat(t('nurse_today_shifts'),'$_todayShiftsCount',Icons.today))]),const SizedBox(height:12),Row(children:[Expanded(child:_stat(t('nurse_earnings'),'${_totalEarnings.toStringAsFixed(0)} ${t('currency_egp')}',Icons.account_balance_wallet_outlined)),const SizedBox(width:12),Expanded(child:_stat(t('nurse_rating'),_averageRating>0?'${_averageRating.toStringAsFixed(1)} ⭐':t('none'),Icons.star_rounded))]),const SizedBox(height:24),Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text(t('nurse_available_requests'),style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold)),TextButton(onPressed:()=>context.push('/nurse/available-requests'),child:Text(t('view_all')))]),const SizedBox(height:8),if(_availableRequests.isEmpty)Card(child:Padding(padding:const EdgeInsets.all(24),child:Column(children:[const Icon(Icons.search_off,size:48),const SizedBox(height:8),Text(t('nurse_no_requests'))])) else ..._availableRequests.take(3).map((r)=>Card(child:ListTile(leading:CircleAvatar(backgroundColor:AppColors.primary,child:Text(r.patientName.isNotEmpty?r.patientName[0]:'?',style:const TextStyle(color:Colors.white))),title:Text(r.patientName),subtitle:Text('${_careType(r.careType)} • ${r.shiftHours} ${t('hours_short')} • ${_governorate(r.governorate)}'),trailing:Icon(LocaleController.instance.isEnglish?Icons.chevron_right:Icons.chevron_left),onTap:()=>context.push('/nurse/request-details/${r.id}'))))]));
 Widget _verificationCard()=>InkWell(onTap:()=>context.push('/nurse/settings'),borderRadius:BorderRadius.circular(12),child:Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.amber.shade50,borderRadius:BorderRadius.circular(12)),child:Row(children:[const Icon(Icons.warning_amber_rounded,color:Colors.amber),const SizedBox(width:10),Expanded(child:Text(t('nurse_complete_verification'))),Icon(LocaleController.instance.isEnglish?Icons.arrow_forward_ios:Icons.arrow_back_ios,size:14)])));
 Widget _stat(String label,String value,IconData icon)=>Card(child:Padding(padding:const EdgeInsets.symmetric(vertical:14,horizontal:8),child:Column(children:[Icon(icon,color:AppColors.primary),const SizedBox(height:6),Text(value,style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold),textAlign:TextAlign.center),Text(label,style:const TextStyle(fontSize:12,color:AppColors.textSecondary),textAlign:TextAlign.center)])));
 String _careType(String v)=>{'elderly':'care_elderly','post_surgery':'care_post_surgery','chronic_disease':'care_chronic','disability':'care_disability','maternity':'care_maternity','general':'care_general'}[v]!=null?t({'elderly':'care_elderly','post_surgery':'care_post_surgery','chronic_disease':'care_chronic','disability':'care_disability','maternity':'care_maternity','general':'care_general'}[v]!):v;
 String _governorate(String v){const en={'القاهرة':'Cairo','الجيزة':'Giza','الإسكندرية':'Alexandria','القليوبية':'Qalyubia','الدقهلية':'Dakahlia','الشرقية':'Sharqia','الغربية':'Gharbia','المنوفية':'Monufia','البحيرة':'Beheira','كفر الشيخ':'Kafr El Sheikh','دمياط':'Damietta','بورسعيد':'Port Said','الإسماعيلية':'Ismailia','السويس':'Suez','الفيوم':'Fayoum','بني سويف':'Beni Suef','المنيا':'Minya','أسيوط':'Assiut','سوهاج':'Sohag','قنا':'Qena','الأقصر':'Luxor','أسوان':'Aswan','مطروح':'Matrouh','الوادي الجديد':'New Valley','شمال سيناء':'North Sinai','جنوب سيناء':'South Sinai','البحر الأحمر':'Red Sea'};return LocaleController.instance.isEnglish?(en[v]??v):v;}
}
