import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/app_strings.dart';
import '../../../core/constants/locale_controller.dart';

class NurseSettingsScreen extends StatefulWidget{const NurseSettingsScreen({super.key});@override State<NurseSettingsScreen> createState()=>_NurseSettingsScreenState();}
class _NurseSettingsScreenState extends State<NurseSettingsScreen>{static const governorates=<String>['القاهرة','الجيزة','الإسكندرية','القليوبية','الدقهلية','الشرقية','الغربية','المنوفية','البحيرة','كفر الشيخ','دمياط','بورسعيد','الإسماعيلية','السويس','الفيوم','بني سويف','المنيا','أسيوط','سوهاج','قنا','الأقصر','أسوان','مطروح','الوادي الجديد','شمال سيناء','جنوب سيناء','البحر الأحمر'];final _firestore=FirebaseFirestore.instance;final _specializationController=TextEditingController();final _experienceController=TextEditingController();final _servicesController=TextEditingController();List<String> _selectedGovernorates=[];bool _loading=true,_saving=false;String t(String k)=>AppStrings.t(k);bool get en=>LocaleController.instance.isEnglish;String tx(String ar,String english)=>en?english:ar;
 @override void initState(){super.initState();_load();}@override void dispose(){_specializationController.dispose();_experienceController.dispose();_servicesController.dispose();super.dispose();}
 Future<void> _load()async{final uid=FirebaseAuth.instance.currentUser?.uid;if(uid==null){if(mounted)setState(()=>_loading=false);return;}try{final doc=await _firestore.collection('nurseProfiles').doc(uid).get();final data=doc.data()??{};final gv=data['preferredGovernorates'];final services=data['services'];_selectedGovernorates=gv is List?gv.map((e)=>e.toString()).toSet().toList():[];_specializationController.text=data['specialization']?.toString()??'';_experienceController.text=data['experienceYears']?.toString()??'';_servicesController.text=services is List?services.map((e)=>e.toString()).join('\n'):(data['servicesText']?.toString()??'');}catch(_){if(mounted)_showMessage(tx('تعذر تحميل إعدادات العمل','Unable to load work settings'));}finally{if(mounted)setState(()=>_loading=false);}}
 Future<void> _save()async{final uid=FirebaseAuth.instance.currentUser?.uid;if(uid==null)return;final experience=int.tryParse(_experienceController.text.trim());if(_selectedGovernorates.isEmpty){_showMessage(tx('اختار محافظة واحدة على الأقل','Select at least one governorate'));return;}if(_specializationController.text.trim().isEmpty){_showMessage(tx('اكتب التخصص','Enter your specialization'));return;}if(experience==null||experience<0||experience>60){_showMessage(tx('اكتب عدد سنوات خبرة صحيح','Enter valid years of experience'));return;}if(_servicesController.text.trim().isEmpty){_showMessage(tx('اكتب الخدمات التي تقدمها','Enter the services you provide'));return;}setState(()=>_saving=true);try{final services=_servicesController.text.split(RegExp(r'[\n,،]+')).map((e)=>e.trim()).where((e)=>e.isNotEmpty).toSet().toList();await _firestore.collection('nurseProfiles').doc(uid).set({'preferredGovernorates':_selectedGovernorates,'specialization':_specializationController.text.trim(),'experienceYears':experience,'services':services,'updatedAt':FieldValue.serverTimestamp()},SetOptions(merge:true));if(mounted)_showMessage(tx('تم حفظ إعدادات العمل بنجاح','Work settings saved successfully'));}catch(_){if(mounted)_showMessage(tx('حدث خطأ أثناء الحفظ، حاول مرة أخرى','An error occurred while saving. Please try again'));}finally{if(mounted)setState(()=>_saving=false);}}
 void _showMessage(String message)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(message)));
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(tx('إعدادات العمل','Work settings'))),body:_loading?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.fromLTRB(16,16,16,32),children:[_section(icon:Icons.location_city_outlined,title:tx('محافظات العمل','Work governorates'),subtitle:tx('اختار المحافظات التي ترغب في استقبال طلبات الرعاية فيها. سيتم فلترة الطلبات بناءً عليها فقط.','Select the governorates where you want to receive care requests. Requests will be filtered accordingly.'),child:Wrap(spacing:8,runSpacing:8,children:governorates.map((g){final selected=_selectedGovernorates.contains(g);return FilterChip(label:Text(_governorate(g)),selected:selected,onSelected:_saving?null:(value)=>setState((){if(value){_selectedGovernorates.add(g);}else{_selectedGovernorates.remove(g);}}));}).toList())),const SizedBox(height:16),_section(icon:Icons.badge_outlined,title:tx('البيانات المهنية','Professional information'),subtitle:tx('هذه البيانات ستظهر للعميل عند مراجعة ملفك.','This information will be shown to clients when they review your profile.'),child:Column(children:[TextField(controller:_specializationController,textInputAction:TextInputAction.next,decoration:InputDecoration(labelText:tx('التخصص','Specialization'),hintText:tx('مثال: تمريض عام، رعاية كبار السن','Example: General nursing, elderly care'),prefixIcon:const Icon(Icons.medical_services_outlined))),const SizedBox(height:12),TextField(controller:_experienceController,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:tx('سنوات الخبرة','Years of experience'),hintText:'5',prefixIcon:const Icon(Icons.workspace_premium_outlined))),const SizedBox(height:12),TextField(controller:_servicesController,minLines:4,maxLines:7,decoration:InputDecoration(labelText:tx('الخدمات التي تقدمها','Services you provide'),hintText:tx('اكتب كل خدمة في سطر أو افصل بينها بفاصلة','Enter each service on a new line or separate with commas'),alignLabelWithHint:true,prefixIcon:const Padding(padding:EdgeInsets.only(bottom:70),child:Icon(Icons.volunteer_activism_outlined))) ])),),const SizedBox(height:16),Card(child:Padding(padding:const EdgeInsets.all(16),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(Icons.info_outline,color:AppColors.primary),const SizedBox(width:12),Expanded(child:Text(tx('الأوراق المطلوبة لإتمام التحقق موجودة في صفحة المستندات: البطاقة، المؤهل الدراسي، وترخيص مزاولة المهنة إن وجد.','Required verification documents are available on the Documents page: ID, educational certificate, and professional license if applicable.'),style:const TextStyle(color:AppColors.textSecondary)))]))),const SizedBox(height:20),SizedBox(height:52,child:FilledButton.icon(onPressed:_saving?null:_save,icon:_saving?const SizedBox(width:20,height:20,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.save_outlined),label:Text(_saving?tx('جاري الحفظ...','Saving...'):tx('حفظ الإعدادات','Save settings'))))]);
 Widget _section({required IconData icon,required String title,required String subtitle,required Widget child})=>Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(icon,color:AppColors.primary),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold)),const SizedBox(height:4),Text(subtitle,style:const TextStyle(color:AppColors.textSecondary))]))]),const SizedBox(height:16),child]));
 String _governorate(String v){const m={'القاهرة':'Cairo','الجيزة':'Giza','الإسكندرية':'Alexandria','القليوبية':'Qalyubia','الدقهلية':'Dakahlia','الشرقية':'Sharqia','الغربية':'Gharbia','المنوفية':'Monufia','البحيرة':'Beheira','كفر الشيخ':'Kafr El Sheikh','دمياط':'Damietta','بورسعيد':'Port Said','الإسماعيلية':'Ismailia','السويس':'Suez','الفيوم':'Fayoum','بني سويف':'Beni Suef','المنيا':'Minya','أسيوط':'Assiut','سوهاج':'Sohag','قنا':'Qena','الأقصر':'Luxor','أسوان':'Aswan','مطروح':'Matrouh','الوادي الجديد':'New Valley','شمال سيناء':'North Sinai','جنوب سيناء':'South Sinai','البحر الأحمر':'Red Sea'};return en?(m[v]??v):v;}
}
