import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/locale_controller.dart';
import '../../shared/models/booking.dart';

class PreviousShiftsScreen extends StatefulWidget{const PreviousShiftsScreen({super.key});@override State<PreviousShiftsScreen> createState()=>_PreviousShiftsScreenState();}
class _PreviousShiftsScreenState extends State<PreviousShiftsScreen> with SingleTickerProviderStateMixin{List<Booking> _shifts=[];bool _loading=true;String? _error;late final TabController _tabs;int _selected=0;bool get en=>LocaleController.instance.isEnglish;String tx(String ar,String english)=>en?english:ar;
 @override void initState(){super.initState();_tabs=TabController(length:3,vsync:this);_load();}@override void dispose(){_tabs.dispose();super.dispose();}
 Future<void> _load()async{if(mounted)setState((){_loading=true;_error=null;});try{final uid=FirebaseAuth.instance.currentUser?.uid;if(uid==null)throw StateError('auth');final s=await FirebaseFirestore.instance.collection('bookings').where('nurseId',isEqualTo:uid).where('status',whereIn:['completed','cancelled','disputed']).limit(50).get();final shifts=s.docs.map(Booking.fromFirestore).toList()..sort((a,b)=>b.createdAt.compareTo(a.createdAt));if(mounted)setState((){_shifts=shifts;_loading=false;});}catch(_){if(mounted)setState((){_error=tx('تعذر تحميل الشيفتات السابقة. حاول مرة أخرى.','Unable to load previous shifts. Please try again.');_loading=false;});}}
 List<Booking> get _filtered{if(_selected==0)return _shifts;final status=_selected==1?'completed':'cancelled';return _shifts.where((s)=>s.status==status).toList();}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(tx('الشيفتات السابقة','Previous shifts')),actions:[IconButton(onPressed:_load,tooltip:tx('تحديث','Refresh'),icon:const Icon(Icons.refresh_outlined))],bottom:TabBar(controller:_tabs,onTap:(i)=>setState(()=>_selected=i),tabs:[Tab(text:tx('الكل','All')),Tab(text:tx('مكتملة','Completed')),Tab(text:tx('ملغاة','Cancelled'))])),body:_loading?const Center(child:CircularProgressIndicator()):_error!=null?_errorState():_filtered.isEmpty?RefreshIndicator(onRefresh:_load,child:ListView(physics:const AlwaysScrollableScrollPhysics(),children:[const SizedBox(height:130),const Icon(Icons.event_busy_outlined,size:60),const SizedBox(height:14),Center(child:Text(tx('لا توجد شيفتات سابقة','No previous shifts'))),const SizedBox(height:6),Center(child:Padding(padding:const EdgeInsets.symmetric(horizontal:24),child:Text(tx('الشيفتات المكتملة أو الملغاة ستظهر هنا.','Completed or cancelled shifts will appear here.'),textAlign:TextAlign.center)))])):RefreshIndicator(onRefresh:_load,child:ListView.separated(padding:const EdgeInsets.all(16),physics:const AlwaysScrollableScrollPhysics(),itemCount:_filtered.length,separatorBuilder:(_,__)=>const SizedBox(height:10),itemBuilder:(_,i)=>_card(_filtered[i]))));
 Widget _errorState()=>Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.cloud_off_outlined,size:56),const SizedBox(height:12),Text(_error!,textAlign:TextAlign.center,style:const TextStyle(color:AppColors.error)),const SizedBox(height:16),FilledButton.icon(onPressed:_load,icon:const Icon(Icons.refresh),label:Text(tx('إعادة المحاولة','Retry')))])));
 Widget _card(Booking shift){final id=shift.id.length>6?shift.id.substring(0,6):shift.id;final completed=shift.status=='completed';final locale=en?'en_US':'ar_EG';return Card(margin:EdgeInsets.zero,child:ListTile(contentPadding:const EdgeInsets.symmetric(horizontal:16,vertical:8),leading:CircleAvatar(backgroundColor:(completed?AppColors.success:AppColors.error).withValues(alpha:.12),child:Icon(completed?Icons.check_circle_outline:Icons.cancel_outlined,color:completed?AppColors.success:AppColors.error)),title:Text('${tx('شيفت','Shift')} #$id',style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text('${DateFormat('dd/MM/yyyy – hh:mm a',locale).format(shift.shiftStart)}\n${shift.totalAmount.toStringAsFixed(2)} ${tx('ج.م','EGP')}'),isThreeLine:true,trailing:Text(completed?tx('مكتمل','Completed'):tx('ملغي','Cancelled'),style:TextStyle(color:completed?AppColors.success:AppColors.error,fontWeight:FontWeight.w700)),onTap:shift.careRequestId.isEmpty?null:()=>context.push('/nurse/request-details/${shift.careRequestId}')));}
}
