import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/app_strings.dart';
import '../../../core/constants/locale_controller.dart';
import '../../shared/models/care_request.dart';

class RequestDetailsNurseScreen extends StatefulWidget {
  final String requestId;
  const RequestDetailsNurseScreen({super.key, required this.requestId});
  @override State<RequestDetailsNurseScreen> createState()=>_RequestDetailsNurseScreenState();
}
class _RequestDetailsNurseScreenState extends State<RequestDetailsNurseScreen>{
  CareRequest? _request; bool _loading=true; bool _sending=false; bool _alreadyApplied=false;
  final _price=TextEditingController(); final _note=TextEditingController();
  String t(String k)=>AppStrings.t(k); bool get en=>LocaleController.instance.isEnglish;
  String tx(String ar,String english)=>en?english:ar;
  @override void initState(){super.initState();_load();}
  Future<void> _load()async{try{final uid=FirebaseAuth.instance.currentUser?.uid;final db=FirebaseFirestore.instance;final snap=await db.collection('careRequests').doc(widget.requestId).get();if(!snap.exists)throw Exception('missing');final request=CareRequest.fromFirestore(snap);if(uid!=null){final offer=await db.collection('careOffers').where('requestId',isEqualTo:widget.requestId).where('nurseId',isEqualTo:uid).limit(1).get();_alreadyApplied=offer.docs.isNotEmpty;}if(mounted)setState((){_request=request;_loading=false;});}catch(_){if(mounted)setState((){_request=null;_loading=false;});}}
  Future<void> _submitOffer()async{final uid=FirebaseAuth.instance.currentUser?.uid;final request=_request;final price=double.tryParse(_price.text.trim());if(uid==null||request==null||price==null||price<=0){_snack(tx('اكتب سعر الشيفت بشكل صحيح','Enter a valid shift price'));return;}if(request.status!='open'){_snack(tx('الطلب لم يعد متاحاً للتقديم','This request is no longer available'));return;}if(_alreadyApplied){_snack(tx('أنت قدمت عرضًا بالفعل على هذا الطلب','You already submitted an offer for this request'));return;}setState(()=>_sending=true);try{final db=FirebaseFirestore.instance;final requestRef=db.collection('careRequests').doc(request.id);final offerRef=db.collection('careOffers').doc('${request.id}_$uid');final userSnap=await db.collection('users').doc(uid).get();final profileSnap=await db.collection('nurseProfiles').doc(uid).get();await db.runTransaction((transaction)async{final requestSnap=await transaction.get(requestRef);final existingOffer=await transaction.get(offerRef);if(!requestSnap.exists||requestSnap.data()?['status']!='open')throw Exception('closed');if(existingOffer.exists)throw Exception('duplicate');final userData=userSnap.data()??{};final profile=profileSnap.data()??{};transaction.set(offerRef,{'requestId':request.id,'clientId':request.clientId,'nurseId':uid,'nurseName':userData['name']??(en?'Nurse':'ممرض'),'nursePhotoUrl':userData['photoUrl'],'nurseRating':(profile['averageRating'] as num?)?.toDouble()??0,'nurseExperienceYears':profile['experienceYears']??0,'nurseSpecialization':profile['specialization']??'','nurseVerified':userData['isVerified']==true,'governorate':request.governorate,'proposedPrice':price,'note':_note.text.trim(),'status':'pending','createdAt':FieldValue.serverTimestamp(),'updatedAt':FieldValue.serverTimestamp()});});if(mounted){setState((){_alreadyApplied=true;_sending=false;});_snack(tx('تم إرسال عرضك للعميل بنجاح','Your offer was sent to the client successfully'));}}catch(e){if(mounted){setState(()=>_sending=false);_snack(tx('تعذر إرسال العرض، حاول مرة أخرى','Unable to send the offer. Please try again'));}}}
  void _snack(String text)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(text)));
  @override void dispose(){_price.dispose();_note.dispose();super.dispose();}
  @override Widget build(BuildContext context){if(_loading)return const Scaffold(body:Center(child:CircularProgressIndicator()));final r=_request;if(r==null)return Scaffold(appBar:AppBar(title:Text(tx('تفاصيل الطلب','Request details'))),body:Center(child:Text(tx('الطلب غير موجود أو لم يعد متاحًا','Request not found or no longer available'))));final locale=en?'en_US':'ar_EG';return Scaffold(appBar:AppBar(title:Text(tx('تفاصيل الطلب','Request details'))),body:RefreshIndicator(onRefresh:_load,child:ListView(padding:const EdgeInsets.all(16),physics:const AlwaysScrollableScrollPhysics(),children:[Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(tx('طلب رعاية','Care request'),style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:12),_row(tx('نوع الرعاية','Care type'),_careType(r.careType)),_row(t('age'),'${r.patientAge} ${tx('سنة','years')}'),_row(t('gender'),r.patientGender=='male'?tx('ذكر','Male'):tx('أنثى','Female')),_row(tx('الشيفت','Shift'),'${r.shiftHours} ${t('hours_short')} × ${r.daysCount} ${t('days_short')}'),_row(t('date'),DateFormat('d/M/yyyy',locale).format(r.startDate)),_row(t('governorate'),_governorate(r.governorate)),_row(t('area'),r.area),if(r.services.isNotEmpty)...[const SizedBox(height:8),Text(r.services.map(_service).join(' • '),style:const TextStyle(color:AppColors.textSecondary))],if(r.notes?.isNotEmpty==true)...[const SizedBox(height:10),Text(r.notes!)] ]))),const SizedBox(height:16),if(_alreadyApplied)Card(color:AppColors.primaryLight,child:Padding(padding:const EdgeInsets.all(18),child:Row(children:[const Icon(Icons.check_circle,color:AppColors.primary),const SizedBox(width:10),Expanded(child:Text(tx('قدمت عرضك بالفعل. انتظر اختيار العميل.','You already submitted an offer. Wait for the client to choose.')))]))) else if(r.status=='open')...[Text(tx('قدم عرضك','Submit your offer'),style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:10),TextField(controller:_price,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:InputDecoration(labelText:tx('سعر الشيفت المقترح','Proposed shift price'),suffixText:t('currency_egp'),prefixIcon:const Icon(Icons.payments_outlined))),const SizedBox(height:12),TextField(controller:_note,maxLines:3,decoration:InputDecoration(labelText:tx('رسالة للعميل (اختياري)','Message to client (optional)'),alignLabelWithHint:true,prefixIcon:const Icon(Icons.message_outlined))),const SizedBox(height:16),SizedBox(height:52,child:FilledButton(onPressed:_sending?null:_submitOffer,child:_sending?const SizedBox(width:22,height:22,child:CircularProgressIndicator(strokeWidth:2,color:Colors.white)):Text(tx('إرسال العرض','Send offer'))))] else Card(child:Padding(padding:const EdgeInsets.all(18),child:Text(tx('هذا الطلب لم يعد متاحاً للتقديم.','This request is no longer available for offers.')))])));}
  Widget _row(String label,String value)=>Padding(padding:const EdgeInsets.symmetric(vertical:5),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[SizedBox(width:95,child:Text(label,style:const TextStyle(fontWeight:FontWeight.bold))),Expanded(child:Text(value))]));
  String _careType(String v){final k={'elderly':'care_elderly','post_surgery':'care_post_surgery','chronic_disease':'care_chronic','disability':'care_disability','maternity':'care_maternity','general':'care_general'}[v];return k==null?v:t(k);}
  String _service(String v){final k={'متابعة الحالة':'service_followup','إعطاء الأدوية':'service_medication','قياس الضغط':'service_bp','قياس السكر':'service_glucose','تغيير الجروح':'service_wound','مساعدة الحركة':'service_mobility','رعاية كبار السن':'service_elderly','رعاية ما بعد العمليات':'service_post_surgery'}[v];return k==null?v:t(k);}
  String _governorate(String v){const enMap={'القاهرة':'Cairo','الجيزة':'Giza','الإسكندرية':'Alexandria','القليوبية':'Qalyubia','الدقهلية':'Dakahlia','الشرقية':'Sharqia','الغربية':'Gharbia','المنوفية':'Monufia','البحيرة':'Beheira','كفر الشيخ':'Kafr El Sheikh','دمياط':'Damietta','بورسعيد':'Port Said','الإسماعيلية':'Ismailia','السويس':'Suez','الفيوم':'Fayoum','بني سويف':'Beni Suef','المنيا':'Minya','أسيوط':'Assiut','سوهاج':'Sohag','قنا':'Qena','الأقصر':'Luxor','أسوان':'Aswan','مطروح':'Matrouh','الوادي الجديد':'New Valley','شمال سيناء':'North Sinai','جنوب سيناء':'South Sinai','البحر الأحمر':'Red Sea'};return en?(enMap[v]??v):v;}
}
