import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:go_router/go_router.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/locale_controller.dart';

class VerificationStatusScreen extends StatefulWidget{const VerificationStatusScreen({super.key});@override State<VerificationStatusScreen> createState()=>_VerificationStatusScreenState();}
class _VerificationStatusScreenState extends State<VerificationStatusScreen>{bool _loading=true;String _status='not_submitted';String? _reason,_error;bool get en=>LocaleController.instance.isEnglish;String tx(String ar,String english)=>en?english:ar;
 @override void initState(){super.initState();_load();}
 Future<void> _load()async{if(mounted)setState((){_loading=true;_error=null;});try{final user=FirebaseAuth.instance.currentUser;if(user==null){if(mounted)setState(()=>_error=tx('يرجى تسجيل الدخول','Please log in'));return;}final doc=await FirebaseFirestore.instance.collection('nurseDocuments').doc(user.uid).get();if(doc.exists){final data=doc.data()!;if(mounted)setState((){_status=data['verificationStatus']??'not_submitted';_reason=data['rejectionReason']?.toString();});}}catch(_){if(mounted)setState(()=>_error=tx('حدث خطأ','Something went wrong'));}finally{if(mounted)setState(()=>_loading=false);}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(tx('حالة التحقق','Verification status'))),body:_loading?const Center(child:CircularProgressIndicator()):_error!=null?Center(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text(_error!,style:const TextStyle(color:AppColors.error)),const SizedBox(height:16),ElevatedButton(onPressed:_load,child:Text(tx('إعادة المحاولة','Retry')))])):Padding(padding:const EdgeInsets.all(24),child:Column(children:[_icon(),const SizedBox(height:24),Text(_label(_status),style:Theme.of(context).textTheme.headlineSmall),const SizedBox(height:8),Text(_description(_status),style:const TextStyle(color:AppColors.textSecondary),textAlign:TextAlign.center),if(_reason!=null)...[const SizedBox(height:16),Container(width:double.infinity,padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Colors.redAccent.withValues(alpha:.08),borderRadius:BorderRadius.circular(8)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(tx('سبب الرفض:','Rejection reason:'),style:const TextStyle(fontWeight:FontWeight.bold)),const SizedBox(height:4),Text(_reason!)]) )],const Spacer(),if(_status=='not_submitted'||_status=='rejected')SizedBox(width:double.infinity,child:ElevatedButton(onPressed:()=>context.go('/nurse/documents'),child:Text(_status=='rejected'?tx('تعديل المستندات','Edit documents'):tx('رفع المستندات','Upload documents')))),if(_status=='approved')SizedBox(width:double.infinity,child:ElevatedButton(onPressed:()=>context.go('/nurse/home'),child:Text(tx('الذهاب للوحة الرئيسية','Go to dashboard')))),const SizedBox(height:16)]));
 Widget _icon(){switch(_status){case'approved':return const Icon(Icons.check_circle,size:80,color:AppColors.success);case'pending':return const Icon(Icons.hourglass_empty,size:80,color:Colors.orange);case'rejected':return const Icon(Icons.cancel,size:80,color:AppColors.error);default:return const Icon(Icons.upload_file,size:80,color:Colors.grey);}}
 String _label(String s){switch(s){case'not_submitted':return tx('لم يتم التقديم','Not submitted');case'pending':return tx('قيد المراجعة','Under review');case'approved':return tx('تم التحقق ✅','Verified ✅');case'rejected':return tx('مرفوض ❌','Rejected ❌');default:return s;}}
 String _description(String s){switch(s){case'not_submitted':return tx('يرجى رفع المستندات المطلوبة للتحقق من حسابك','Upload the required documents to verify your account');case'pending':return tx('نحن نراجع مستنداتك، سيتم إعلامك عند الانتهاء','We are reviewing your documents. You will be notified when the review is complete');case'approved':return tx('تهانينا! حسابك موثق ويمكنك استقبال الطلبات الآن','Congratulations! Your account is verified and you can receive requests now');case'rejected':return tx('يوجد مشكلة في المستندات، يرجى تعديلها وإعادة الإرسال','There is an issue with your documents. Please edit and resubmit them');default:return '';}}
}
