import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/app_strings.dart';
import '../../../core/constants/locale_controller.dart';
import '../../../services/auth_service.dart';
import '../../../services/user_service.dart';
import '../../../services/shared_preferences_service.dart';
import '../../shared/models/app_user.dart';

class ClientProfileScreen extends StatefulWidget { const ClientProfileScreen({super.key}); @override State<ClientProfileScreen> createState()=>_ClientProfileScreenState(); }
class _ClientProfileScreenState extends State<ClientProfileScreen>{AppUser? _user;bool _isLoading=true;String? _errorMessage;String t(String k)=>AppStrings.t(k);
 @override void initState(){super.initState();_loadUser();}
 Future<void> _loadUser()async{if(mounted)setState((){_isLoading=true;_errorMessage=null;});try{final user=AuthService().currentUser;if(user==null){if(mounted)setState(()=>_errorMessage=t('login_required'));return;}final appUser=await UserService().getUser(user.uid);if(mounted)setState(()=>_user=appUser);}catch(_){if(mounted)setState(()=>_errorMessage=t('error_generic'));}finally{if(mounted)setState(()=>_isLoading=false);}}
 Future<void> _editInfo()async{if(_user==null)return;final nameController=TextEditingController(text:_user!.name);final phoneController=TextEditingController(text:_user!.phone);final saved=await showDialog<bool>(context:context,builder:(context)=>AlertDialog(title:Text(t('edit_info')),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:nameController,decoration:InputDecoration(labelText:t('full_name'))),const SizedBox(height:12),TextField(controller:phoneController,keyboardType:TextInputType.phone,decoration:InputDecoration(labelText:t('phone_number')))]),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:Text(t('cancel'))),FilledButton(onPressed:()=>Navigator.pop(context,true),child:Text(t('save')))]));if(saved!=true){nameController.dispose();phoneController.dispose();return;}final newName=nameController.text.trim();final newPhone=phoneController.text.trim();nameController.dispose();phoneController.dispose();if(newName.isEmpty||newPhone.isEmpty){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(t('required_field'))));return;}try{await UserService().updateUser(_user!.uid,{'name':newName,'phone':newPhone});if(!mounted)return;setState(()=>_user=_user!.copyWith(name:newName,phone:newPhone));ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(t('saved'))));}catch(_){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(t('error_generic'))));}}
 void _showHelp(){showDialog<void>(context:context,builder:(context)=>AlertDialog(title:Text(t('help')),content:Text(t('help_desc')),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:Text(t('ok')))]));}
 Future<void> _logout()async{await AuthService().logout();await SharedPreferencesService().clearTempPreferences();if(mounted)context.go('/login');}
 @override Widget build(BuildContext context){return Scaffold(backgroundColor:AppColors.background,appBar:AppBar(title:Text(t('my_account'))),body:_isLoading?const Center(child:CircularProgressIndicator()):_errorMessage!=null||_user==null?Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Text(_errorMessage??t('no_data')),const SizedBox(height:12),FilledButton(onPressed:_loadUser,child:Text(t('retry')))])):RefreshIndicator(onRefresh:_loadUser,child:ListView(padding:const EdgeInsets.all(16),children:[Card(margin:EdgeInsets.zero,child:Padding(padding:const EdgeInsets.all(20),child:Column(children:[CircleAvatar(radius:46,backgroundColor:AppColors.primary,child:Text(_user!.name.isNotEmpty?_user!.name[0]:'?',style:const TextStyle(fontSize:36,color:Colors.white))),const SizedBox(height:12),Text(_user!.name,style:Theme.of(context).textTheme.headlineSmall),const SizedBox(height:4),Text(_user!.phone,style:const TextStyle(color:AppColors.textSecondary)),if((_user!.email??'').isNotEmpty)Text(_user!.email!,style:const TextStyle(color:AppColors.textSecondary))])),const SizedBox(height:16),_buildLanguageToggle(),const SizedBox(height:8),_buildMenuItem(Icons.edit_outlined,t('edit_info'),_editInfo),_buildMenuItem(Icons.history,t('my_bookings'),()=>context.push('/client/my-bookings')),_buildMenuItem(Icons.list_alt_outlined,t('my_requests'),()=>context.push('/client/my-requests')),_buildMenuItem(Icons.chat_bubble_outline,t('nav_messages'),()=>context.push('/client/messages')),_buildMenuItem(Icons.help_outline,t('help'),_showHelp),const SizedBox(height:8),_buildMenuItem(Icons.logout,t('logout'),_logout,isDestructive:true)]));}
 Widget _buildLanguageToggle(){final isEnglish=LocaleController.instance.isEnglish;return Card(margin:EdgeInsets.zero,child:ListTile(leading:const Icon(Icons.language,color:AppColors.primary),title:Text(t('language')),trailing:Row(mainAxisSize:MainAxisSize.min,children:[Text(isEnglish?t('english'):t('arabic')),Switch(value:isEnglish,onChanged:(value)=>LocaleController.instance.setLocale(value?const Locale('en','US'):const Locale('ar','EG')))]));}
 Widget _buildMenuItem(IconData icon,String title,VoidCallback onTap,{bool isDestructive=false})=>Card(margin:const EdgeInsets.only(bottom:8),child:ListTile(leading:Icon(icon,color:isDestructive?AppColors.error:AppColors.primary),title:Text(title,style:TextStyle(color:isDestructive?AppColors.error:null,fontWeight:FontWeight.w500)),trailing:Icon(LocaleController.instance.isEnglish?Icons.arrow_forward_ios:Icons.arrow_back_ios,size:16),onTap:onTap));
}
