import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/app_strings.dart';
import '../../../core/constants/locale_controller.dart';
import '../../../services/auth_service.dart';
import '../../../services/care_request_service.dart';
import '../../../services/user_service.dart';
import '../../shared/models/app_user.dart';
import '../../shared/models/care_request.dart';

class ClientHomeScreen extends StatefulWidget{const ClientHomeScreen({super.key});@override State<ClientHomeScreen> createState()=>_ClientHomeScreenState();}
class _ClientHomeScreenState extends State<ClientHomeScreen>{AppUser? _user;List<CareRequest> _requests=[];bool _loading=true;String? _error;String t(String k)=>AppStrings.t(k);bool get en=>LocaleController.instance.isEnglish;
 @override void initState(){super.initState();_load();}
 Future<void> _load()async{if(mounted)setState((){_loading=true;_error=null;});try{final u=AuthService().currentUser;if(u==null)throw Exception('auth');final results=await Future.wait([UserService().getUser(u.uid),CareRequestService().getClientRequests(u.uid)]);if(mounted)setState((){_user=results[0] as AppUser?;_requests=results[1] as List<CareRequest>;});}catch(_){if(mounted)setState(()=>_error=t('error_load_home'));}finally{if(mounted)setState(()=>_loading=false);}}
 @override Widget build(BuildContext context){final name=_user?.name.trim().isNotEmpty==true?_user!.name.trim():t('role_client');return Scaffold(backgroundColor:AppColors.background,appBar:AppBar(automaticallyImplyLeading:false,title:Text(t('nav_home')),actions:[IconButton(tooltip:t('logout'),onPressed:()async{await AuthService().logout();if(context.mounted)context.go('/login');},icon:const Icon(Icons.logout_outlined))]),body:_loading?const Center(child:CircularProgressIndicator()):_error!=null?_errorView():RefreshIndicator(onRefresh:_load,child:ListView(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.fromLTRB(16,8,16,24),children:[_welcome(name),const SizedBox(height:16),_requestCare(),const SizedBox(height:16),_shortcut(),const SizedBox(height:12),Row(children:[Expanded(child:_quick(Icons.calendar_month_outlined,t('nav_bookings'),()=>context.go('/client/my-bookings'))),const SizedBox(width:12),Expanded(child:_quick(Icons.chat_bubble_outline,t('nav_messages'),()=>context.go('/client/messages')))]),const SizedBox(height:24),Row(children:[Expanded(child:Text(t('my_recent_requests'),style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w700))),if(_requests.isNotEmpty)TextButton(onPressed:()=>context.go('/client/my-requests'),child:Text(t('view_all')))]),const SizedBox(height:8),if(_requests.isEmpty)_empty()else..._requests.take(3).map(_requestCard)]));}
 Widget _errorView()=>Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.cloud_off_outlined,size:48),const SizedBox(height:12),Text(_error!,textAlign:TextAlign.center),const SizedBox(height:16),FilledButton.icon(onPressed:_load,icon:const Icon(Icons.refresh),label:Text(t('retry')))])));
 Widget _welcome(String name)=>Card(margin:EdgeInsets.zero,child:Padding(padding:const EdgeInsets.all(20),child:Row(children:[const CircleAvatar(radius:28,child:Icon(Icons.person_outline,size:30)),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${t('welcome_hi')} $name 👋',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w700)),const SizedBox(height:4),Text(t('welcome_subtitle'))]))])));
 Widget _requestCare()=>Card(margin:EdgeInsets.zero,child:Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Icon(Icons.medical_services_outlined,size:34),const SizedBox(height:12),Text(t('need_nurse_title'),style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w800)),const SizedBox(height:6),Text(t('need_nurse_desc')),const SizedBox(height:16),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:()=>context.push('/client/create-request'),icon:const Icon(Icons.add_circle_outline),label:Text(t('request_care_action'))))])));
 Widget _shortcut()=>Card(margin:EdgeInsets.zero,child:InkWell(borderRadius:BorderRadius.circular(16),onTap:()=>context.go('/client/my-requests'),child:Padding(padding:const EdgeInsets.all(16),child:Row(children:[Container(width:48,height:48,decoration:BoxDecoration(color:AppColors.primary.withValues(alpha:.10),borderRadius:BorderRadius.circular(14)),child:const Icon(Icons.assignment_outlined)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t('nav_care_requests'),style:const TextStyle(fontSize:17,fontWeight:FontWeight.w800)),const SizedBox(height:3),Text(t('care_requests_shortcut_desc'),style:const TextStyle(color:AppColors.textSecondary,fontSize:12))])),Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:6),decoration:BoxDecoration(color:AppColors.primaryLight,borderRadius:BorderRadius.circular(20)),child:Text('${_requests.length}',style:const TextStyle(fontWeight:FontWeight.w800))),const SizedBox(width:4),Icon(en?Icons.chevron_right:Icons.chevron_left)]))));
 Widget _quick(IconData icon,String title,VoidCallback tap)=>Card(margin:EdgeInsets.zero,child:InkWell(borderRadius:BorderRadius.circular(16),onTap:tap,child:Padding(padding:const EdgeInsets.symmetric(vertical:16),child:Row(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(icon,size:25),const SizedBox(width:8),Text(title,style:const TextStyle(fontWeight:FontWeight.w700))]))));
 Widget _empty()=>Card(margin:EdgeInsets.zero,child:Padding(padding:const EdgeInsets.all(18),child:Column(children:[const Icon(Icons.post_add_outlined,size:42),const SizedBox(height:8),Text(t('no_requests_yet')),const SizedBox(height:10),OutlinedButton(onPressed:()=>context.push('/client/create-request'),child:Text(t('create_request_short')))])));
 Widget _requestCard(CareRequest r){final status=_status(r.status);final locale=en?'en_US':'ar_EG';return Card(margin:const EdgeInsets.only(bottom:10),child:InkWell(borderRadius:BorderRadius.circular(16),onTap:()=>context.push('/client/request-details/${r.id}'),child:Padding(padding:const EdgeInsets.all(15),child:Row(children:[CircleAvatar(backgroundColor:AppColors.primaryLight,child:const Icon(Icons.medical_services_outlined)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(_careType(r.careType),style:const TextStyle(fontWeight:FontWeight.w700)),const SizedBox(height:4),Text('${r.shiftHours} ${t('hours_short')} × ${r.daysCount} ${t('days_short')} • ${_governorate(r.governorate)}',style:const TextStyle(color:AppColors.textSecondary,fontSize:12)),const SizedBox(height:3),Text(DateFormat('d/M/yyyy',locale).format(r.startDate),style:const TextStyle(color:AppColors.textSecondary,fontSize:12))])),_Badge(text:status.$1,color:status.$2)]))));}
 (String,Color) _status(String s)=>switch(s){'open'=>(t('status_open'),AppColors.primary),'booked'=>(t('status_booked'),Colors.blue),'in_progress'=>(t('status_in_progress'),Colors.orange),'completed'=>(t('status_completed'),Colors.green),'cancelled'=>(t('status_cancelled'),AppColors.error),_=>(t('status_pending'),Colors.grey)};
 String _careType(String v){final k={'elderly':'care_elderly','post_surgery':'care_post_surgery','chronic_disease':'care_chronic','disability':'care_disability','maternity':'care_maternity','general':'care_general'}[v];return k==null?v:t(k);}
 String _governorate(String v){const m={'القاهرة':'Cairo','الجيزة':'Giza','الإسكندرية':'Alexandria','القليوبية':'Qalyubia','الدقهلية':'Dakahlia','الشرقية':'Sharqia','الغربية':'Gharbia','المنوفية':'Monufia','البحيرة':'Beheira','كفر الشيخ':'Kafr El Sheikh','دمياط':'Damietta','بورسعيد':'Port Said','الإسماعيلية':'Ismailia','السويس':'Suez','الفيوم':'Fayoum','بني سويف':'Beni Suef','المنيا':'Minya','أسيوط':'Assiut','سوهاج':'Sohag','قنا':'Qena','الأقصر':'Luxor','أسوان':'Aswan','مطروح':'Matrouh','الوادي الجديد':'New Valley','شمال سيناء':'North Sinai','جنوب سيناء':'South Sinai','البحر الأحمر':'Red Sea'};return en?(m[v]??v):v;}
}
class _Badge extends StatelessWidget{final String text;final Color color;const _Badge({required this.text,required this.color});@override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.symmetric(horizontal:8,vertical:5),decoration:BoxDecoration(color:color.withValues(alpha:.12),borderRadius:BorderRadius.circular(20)),child:Text(text,style:TextStyle(color:color,fontSize:10,fontWeight:FontWeight.bold)));}
