import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/app_strings.dart';
import '../../../core/constants/locale_controller.dart';
import '../../../services/auth_service.dart';
import '../../../services/user_service.dart';
import '../../shared/models/app_user.dart';

class ClientMessagesScreen extends StatefulWidget { const ClientMessagesScreen({super.key}); @override State<ClientMessagesScreen> createState()=>_ClientMessagesScreenState(); }
class _ClientMessagesScreenState extends State<ClientMessagesScreen>{bool _isLoading=true;String? _errorMessage;List<QueryDocumentSnapshot<Map<String,dynamic>>> _chats=[];Map<String,AppUser> _nurses={};String t(String k)=>AppStrings.t(k);
 @override void initState(){super.initState();_loadChats();}
 Future<void> _loadChats()async{if(mounted)setState((){_isLoading=true;_errorMessage=null;});try{final user=AuthService().currentUser;if(user==null){if(mounted)setState(()=>_errorMessage=t('login_required'));return;}final snapshot=await FirebaseFirestore.instance.collection('chats').where('clientId',isEqualTo:user.uid).limit(30).get();final chats=[...snapshot.docs]..sort((a,b){final at=a.data()['updatedAt'];final bt=b.data()['updatedAt'];if(at is Timestamp&&bt is Timestamp)return bt.compareTo(at);return 0;});final ids=chats.map((d)=>d.data()['nurseId']?.toString()??'').where((id)=>id.isNotEmpty);final nurses=await UserService().getUsersByIds(ids);if(mounted)setState((){_chats=chats;_nurses=nurses;});}catch(_){if(mounted)setState(()=>_errorMessage=t('messages_load_error'));}finally{if(mounted)setState(()=>_isLoading=false);}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(automaticallyImplyLeading:false,title:Text(t('nav_messages')),actions:[IconButton(tooltip:t('retry'),onPressed:_loadChats,icon:const Icon(Icons.refresh))]),body:_buildBody(context));
 Widget _buildBody(BuildContext context){if(_isLoading)return const Center(child:CircularProgressIndicator());if(_errorMessage!=null)return Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.cloud_off_outlined,size:48,color:AppColors.error),const SizedBox(height:12),Text(_errorMessage!,textAlign:TextAlign.center),const SizedBox(height:16),FilledButton.icon(onPressed:_loadChats,icon:const Icon(Icons.refresh),label:Text(t('retry')))])));if(_chats.isEmpty)return RefreshIndicator(onRefresh:_loadChats,child:ListView(physics:const AlwaysScrollableScrollPhysics(),children:[const SizedBox(height:120),const Icon(Icons.chat_bubble_outline,size:64),const SizedBox(height:16),Center(child:Text(t('no_conversations'),style:const TextStyle(fontSize:18,fontWeight:FontWeight.w700))),const SizedBox(height:8),Center(child:Padding(padding:const EdgeInsets.symmetric(horizontal:24),child:Text(t('no_conversations_desc'),textAlign:TextAlign.center)))]));return RefreshIndicator(onRefresh:_loadChats,child:ListView.separated(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.all(16),itemCount:_chats.length,separatorBuilder:(_,__)=>const SizedBox(height:8),itemBuilder:(context,index){final data=_chats[index].data();final bookingId=data['bookingId'] as String?;final nurseId=data['nurseId']?.toString();final nurse=nurseId!=null?_nurses[nurseId]:null;final displayName=nurse?.name.trim().isNotEmpty==true?nurse!.name.trim():t('conversation');final lastMessage=data['lastMessage'] as String?;final updatedAt=data['updatedAt'];final dateText=updatedAt is Timestamp?_formatDate(updatedAt.toDate()):'';return Card(margin:EdgeInsets.zero,child:ListTile(contentPadding:const EdgeInsets.symmetric(horizontal:16,vertical:8),leading:CircleAvatar(backgroundColor:AppColors.primaryLight,backgroundImage:(nurse?.photoUrl?.isNotEmpty??false)?NetworkImage(nurse!.photoUrl!):null,child:(nurse?.photoUrl?.isNotEmpty??false)?null:Icon(Icons.person_outline,color:AppColors.primary)),title:Text(displayName,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text(lastMessage?.trim().isNotEmpty==true?lastMessage!:t('start_conversation'),maxLines:1,overflow:TextOverflow.ellipsis),trailing:dateText.isEmpty?Icon(LocaleController.instance.isEnglish?Icons.chevron_right:Icons.chevron_left):Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text(dateText,style:const TextStyle(fontSize:11)),Icon(LocaleController.instance.isEnglish?Icons.chevron_right:Icons.chevron_left,size:18)]),onTap:bookingId==null?null:()=>context.push('/client/chat/$bookingId'))); }));}
 String _formatDate(DateTime date){final now=DateTime.now();if(now.year==date.year&&now.month==date.month&&now.day==date.day)return '${date.hour.toString().padLeft(2,'0')}:${date.minute.toString().padLeft(2,'0')}';final locale=LocaleController.instance.isEnglish?'en_US':'ar_EG';return '${date.day}/${date.month}/${date.year}';}
}
