import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/app_strings.dart';
import '../../../core/constants/locale_controller.dart';
import '../../../services/booking_service.dart';
import '../../../services/auth_service.dart';
import '../../shared/models/booking.dart';

class MyBookingsScreen extends StatefulWidget{const MyBookingsScreen({super.key});@override State<MyBookingsScreen> createState()=>_MyBookingsScreenState();}
class _MyBookingsScreenState extends State<MyBookingsScreen> with SingleTickerProviderStateMixin{List<Booking> _bookings=[];bool _isLoading=true;String? _errorMessage;late final TabController _tabController;String t(String k)=>AppStrings.t(k);
 @override void initState(){super.initState();_tabController=TabController(length:4,vsync:this);_loadBookings();}
 @override void dispose(){_tabController.dispose();super.dispose();}
 Future<void> _loadBookings()async{if(mounted)setState((){_isLoading=true;_errorMessage=null;});try{final user=AuthService().currentUser;if(user==null){if(mounted)setState(()=>_errorMessage=t('login_required'));return;}final bookings=await BookingService().getClientBookings(user.uid);if(mounted)setState(()=>_bookings=bookings);}catch(_){if(mounted)setState(()=>_errorMessage=t('bookings_load_error'));}finally{if(mounted)setState(()=>_isLoading=false);}}
 List<Booking> _bookingsForTab(int i){switch(i){case 1:return _bookings.where((b)=>b.status=='pending_payment'||b.status=='confirmed'||b.status=='in_progress').toList();case 2:return _bookings.where((b)=>b.status=='completed').toList();case 3:return _bookings.where((b)=>b.status=='cancelled').toList();default:return _bookings;}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(automaticallyImplyLeading:false,title:Text(t('my_bookings')),bottom:TabBar(controller:_tabController,isScrollable:true,tabs:[Tab(text:t('all')),Tab(text:t('upcoming')),Tab(text:t('previous')),Tab(text:t('cancelled'))])),body:_buildBody());
 Widget _buildBody(){if(_isLoading)return const Center(child:CircularProgressIndicator());if(_errorMessage!=null)return Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.cloud_off_outlined,size:48,color:AppColors.error),const SizedBox(height:12),Text(_errorMessage!,textAlign:TextAlign.center),const SizedBox(height:16),FilledButton.icon(onPressed:_loadBookings,icon:const Icon(Icons.refresh),label:Text(t('retry')))])));return RefreshIndicator(onRefresh:_loadBookings,child:TabBarView(controller:_tabController,children:List.generate(4,(i)=>_buildList(_bookingsForTab(i)))));}
 Widget _buildList(List<Booking> list){if(list.isEmpty)return ListView(physics:const AlwaysScrollableScrollPhysics(),children:[const SizedBox(height:120),const Icon(Icons.event_busy_outlined,size:60),const SizedBox(height:14),Center(child:Text('')) ,Center(child:Text(t('no_bookings_here'),style:const TextStyle(fontSize:18,fontWeight:FontWeight.w700))),const SizedBox(height:6),Center(child:Text(t('booking_will_appear_here')))]);final locale=LocaleController.instance.isEnglish?'en_US':'ar_EG';return ListView.separated(padding:const EdgeInsets.all(16),physics:const AlwaysScrollableScrollPhysics(),itemCount:list.length,separatorBuilder:(_,__)=>const SizedBox(height:10),itemBuilder:(context,index){final b=list[index];final id=b.id.length<=6?b.id:b.id.substring(0,6);return Card(margin:EdgeInsets.zero,child:InkWell(borderRadius:BorderRadius.circular(16),onTap:()=>context.push('/client/booking-details/${b.id}'),child:Padding(padding:const EdgeInsets.all(16),child:Row(children:[const CircleAvatar(child:Icon(Icons.medical_services_outlined)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${t('booking_number')}$id',style:const TextStyle(fontWeight:FontWeight.w700)),const SizedBox(height:6),Text('${DateFormat('dd/MM/yyyy – hh:mm a',locale).format(b.shiftStart)}\n${b.totalAmount.toStringAsFixed(2)} ${t('currency_egp')}')])) ,const SizedBox(width:8),_StatusBadge(label:_getStatusLabel(b.status),color:_getStatusColor(b.status)),const SizedBox(width:4),Icon(LocaleController.instance.isEnglish?Icons.chevron_right:Icons.chevron_left)]))));});}
 Color _getStatusColor(String s){switch(s){case 'pending_payment':return Colors.orange;case 'confirmed':return Colors.blue;case 'in_progress':return Colors.purple;case 'completed':return Colors.green;case 'cancelled':return Colors.red;default:return Colors.grey;}}
 String _getStatusLabel(String s){switch(s){case 'pending_payment':return t('status_pending_payment');case 'confirmed':return t('status_confirmed');case 'in_progress':return t('status_in_progress');case 'completed':return t('status_completed');case 'cancelled':return t('status_cancelled');default:return t('status_unknown');}}
}
class _StatusBadge extends StatelessWidget{final String label;final Color color;const _StatusBadge({required this.label,required this.color});@override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.symmetric(horizontal:9,vertical:5),decoration:BoxDecoration(color:color.withValues(alpha:.12),borderRadius:BorderRadius.circular(20)),child:Text(label,style:TextStyle(color:color,fontSize:11,fontWeight:FontWeight.w700)));}
