import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/app_strings.dart';
import '../../../core/constants/locale_controller.dart';
import '../../../services/auth_service.dart';
import '../../../services/care_request_service.dart';
import '../../shared/models/care_request.dart';

class MyRequestsScreen extends StatefulWidget { const MyRequestsScreen({super.key}); @override State<MyRequestsScreen> createState()=>_MyRequestsScreenState(); }
class _MyRequestsScreenState extends State<MyRequestsScreen>{bool _loading=true;String? _error;List<CareRequest> _requests=[];String t(String k)=>AppStrings.t(k);
 @override void initState(){super.initState();_load();}
 Future<void> _load()async{if(mounted)setState((){_loading=true;_error=null;});try{final uid=AuthService().currentUser?.uid;if(uid==null)throw Exception('auth');final requests=await CareRequestService().getClientRequests(uid);if(mounted)setState((){_requests=requests;_loading=false;});}catch(_){if(mounted)setState((){_error=t('care_requests_load_error');_loading=false;});}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(t('nav_care_requests')),actions:[IconButton(onPressed:_load,tooltip:t('retry'),icon:const Icon(Icons.refresh))]),body:_loading?const Center(child:CircularProgressIndicator()):_error!=null?_errorView():RefreshIndicator(onRefresh:_load,child:_requests.isEmpty?_empty():ListView.separated(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.fromLTRB(16,16,16,28),itemCount:_requests.length,separatorBuilder:(_,__)=>const SizedBox(height:12),itemBuilder:(_,i)=>_card(_requests[i]))));
 Widget _card(CareRequest request){final shortId=request.id.length>6?request.id.substring(0,6):request.id;final status=_status(request.status);final canSeeOffers=request.status=='open';final hasSelectedNurse={'booked','in_progress','completed'}.contains(request.status);final locale=LocaleController.instance.isEnglish?'en_US':'ar_EG';return Card(margin:EdgeInsets.zero,clipBehavior:Clip.antiAlias,child:InkWell(onTap:()=>context.push('/client/request-details/${request.id}'),child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[CircleAvatar(backgroundColor:AppColors.primaryLight,child:Icon(Icons.medical_services_outlined,color:AppColors.primary)),const SizedBox(width:12),Expanded(child:Text('${t('request_number')}$shortId',style:const TextStyle(fontWeight:FontWeight.bold,fontSize:16))),_Badge(text:status.$1,color:status.$2)]),const SizedBox(height:12),Text(t(_careTypeKey(request.careType)),style:const TextStyle(fontWeight:FontWeight.w700,fontSize:16)),const SizedBox(height:7),Text('${request.shiftHours} ${t('hours_short')} × ${request.daysCount} ${t('days_short')} • ${_governorate(request.governorate)} - ${request.area}',style:const TextStyle(color:AppColors.textSecondary)),const SizedBox(height:5),Text(DateFormat('d/M/yyyy',locale).format(request.startDate),style:const TextStyle(color:AppColors.textSecondary,fontSize:12)),const SizedBox(height:14),if(canSeeOffers)SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:()=>context.push('/client/request-offers/${request.id}'),icon:const Icon(Icons.people_outline),label:Text(t('view_nurse_offers'))))else if(hasSelectedNurse)SizedBox(width:double.infinity,child:OutlinedButton.icon(onPressed:()=>context.push('/client/request-offers/${request.id}'),icon:const Icon(Icons.person_search_outlined),label:Text(t('view_selected_nurse'))))]))));}
 Widget _empty()=>ListView(physics:const AlwaysScrollableScrollPhysics(),children:[const SizedBox(height:110),const Icon(Icons.post_add_outlined,size:64),const SizedBox(height:14),Center(child:Text(t('no_care_requests'),style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold))),const SizedBox(height:8),Center(child:Padding(padding:const EdgeInsets.symmetric(horizontal:30),child:Text(t('no_care_requests_desc'),textAlign:TextAlign.center))),const SizedBox(height:20),Center(child:FilledButton.icon(onPressed:()=>context.push('/client/create-request'),icon:const Icon(Icons.add),label:Text(t('create_request'))))]);
 Widget _errorView()=>Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.cloud_off_outlined,size:52,color:AppColors.error),const SizedBox(height:12),Text(_error!,textAlign:TextAlign.center),const SizedBox(height:16),FilledButton.icon(onPressed:_load,icon:const Icon(Icons.refresh),label:Text(t('retry')))])));
 (String,Color) _status(String value){switch(value){case 'open':return(t('status_open'),AppColors.primary);case 'booked':return(t('status_booked'),Colors.blue);case 'in_progress':return(t('status_in_progress'),Colors.orange);case 'completed':return(t('status_completed'),Colors.green);case 'cancelled':return(t('status_cancelled'),AppColors.error);default:return(t('status_pending'),Colors.grey);}}
 String _careTypeKey(String v)=>{'elderly':'care_elderly','post_surgery':'care_post_surgery','chronic_disease':'care_chronic','disability':'care_disability','maternity':'care_maternity','general':'care_general'}[v]??v;
 String _governorate(String v){const en={'القاهرة':'Cairo','الجيزة':'Giza','الإسكندرية':'Alexandria','القليوبية':'Qalyubia','الدقهلية':'Dakahlia','الشرقية':'Sharqia','الغربية':'Gharbia','المنوفية':'Monufia','البحيرة':'Beheira','كفر الشيخ':'Kafr El Sheikh','دمياط':'Damietta','بورسعيد':'Port Said','الإسماعيلية':'Ismailia','السويس':'Suez','الفيوم':'Fayoum','بني سويف':'Beni Suef','المنيا':'Minya','أسيوط':'Assiut','سوهاج':'Sohag','قنا':'Qena','الأقصر':'Luxor','أسوان':'Aswan','مطروح':'Matrouh','الوادي الجديد':'New Valley','شمال سيناء':'North Sinai','جنوب سيناء':'South Sinai','البحر الأحمر':'Red Sea'};return LocaleController.instance.isEnglish?(en[v]??v):v;}
}
class _Badge extends StatelessWidget{final String text;final Color color;const _Badge({required this.text,required this.color});@override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.symmetric(horizontal:9,vertical:5),decoration:BoxDecoration(color:color.withValues(alpha:.12),borderRadius:BorderRadius.circular(20)),child:Text(text,style:TextStyle(color:color,fontSize:11,fontWeight:FontWeight.bold)));}
