import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:intl/intl.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/app_strings.dart';
import '../../../core/constants/locale_controller.dart';
import '../../../services/care_request_service.dart';
import '../../../services/auth_service.dart';
import '../../shared/models/care_request.dart';

class RequestDetailsScreen extends StatefulWidget { final String requestId; const RequestDetailsScreen({super.key,required this.requestId}); @override State<RequestDetailsScreen> createState()=>_RequestDetailsScreenState(); }
class _RequestDetailsScreenState extends State<RequestDetailsScreen>{ CareRequest? _request; bool _isLoading=true; String? _errorMessage; int _offerCount=0; String? _bookingId; String t(String k)=>AppStrings.t(k);
 @override void initState(){super.initState();_loadRequest();}
 Future<void> _loadRequest() async {if(mounted)setState((){_isLoading=true;_errorMessage=null;});try{final uid=AuthService().currentUser?.uid;final req=await CareRequestService().getRequest(widget.requestId);if(req==null||req.clientId!=uid)throw Exception('not found');final db=FirebaseFirestore.instance;final offers=await db.collection('careOffers').where('requestId',isEqualTo:widget.requestId).where('status',isEqualTo:'pending').limit(50).get();String? bookingId;if({'booked','in_progress','completed'}.contains(req.status)){final bookings=await db.collection('bookings').where('careRequestId',isEqualTo:widget.requestId).limit(5).get();for(final doc in bookings.docs){if(doc.data()['clientId']==uid){bookingId=doc.id;break;}}}if(mounted)setState((){_request=req;_offerCount=offers.docs.length;_bookingId=bookingId;_isLoading=false;});}catch(_){if(mounted)setState((){_errorMessage=t('request_load_error');_isLoading=false;});}}
 @override Widget build(BuildContext context){final request=_request;final locale=LocaleController.instance.isEnglish?'en_US':'ar_EG';return Scaffold(appBar:AppBar(title:Text(t('request_details')),actions:[IconButton(onPressed:_loadRequest,tooltip:t('retry'),icon:const Icon(Icons.refresh))]),body:_isLoading?const Center(child:CircularProgressIndicator()):_errorMessage!=null?Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Text(_errorMessage!,style:const TextStyle(color:AppColors.error)),const SizedBox(height:12),FilledButton(onPressed:_loadRequest,child:Text(t('retry')))])):request==null?Center(child:Text(t('request_not_found'))):RefreshIndicator(onRefresh:_loadRequest,child:ListView(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.all(16),children:[_statusCard(request.status),const SizedBox(height:12),Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[_row(t('patient_name'),request.patientName),_row(t('age'),'${request.patientAge} ${t('years_short')}'),_row(t('gender'),request.patientGender=='male'?t('male'):t('female')),_row(t('care_type'),t(_careTypeKey(request.careType))),_row(t('shift'),'${request.shiftHours} ${t('hours_short')} × ${request.daysCount} ${t('days_short')}'),_row(t('date'),DateFormat.yMd(locale).format(request.startDate)),_row(t('time'),'${request.startTime.hour.toString().padLeft(2,'0')}:${request.startTime.minute.toString().padLeft(2,'0')}'),_row(t('governorate'),_governorate(request.governorate)),_row(t('area'),request.area),_row(t('full_address'),request.address),const SizedBox(height:8),Text(t('requested_services'),style:const TextStyle(fontWeight:FontWeight.bold)),const SizedBox(height:6),Wrap(spacing:6,runSpacing:6,children:request.services.map((s)=>Chip(label:Text(t(_serviceKey(s))))).toList()),if(request.notes?.isNotEmpty==true)...[const SizedBox(height:8),Text(t('extra_notes'),style:const TextStyle(fontWeight:FontWeight.bold)),Text(request.notes!)] ]))),const SizedBox(height:14),if(request.status=='open'||request.status=='matching')SizedBox(height:52,child:FilledButton.icon(onPressed:()=>context.push('/client/request-offers/${request.id}'),icon:const Icon(Icons.people_outline),label:Text(_offerCount==0?t('waiting_nurse_offers'):'${t('view_offers_count')} $_offerCount'))),if(request.status=='open')... [const SizedBox(height:10),OutlinedButton.icon(onPressed:()=>context.push('/client/nurse-results/${request.id}'),icon:const Icon(Icons.search),label:Text(t('browse_nurses')))],if(_bookingId!=null)...[const SizedBox(height:10),SizedBox(height:52,child:FilledButton.icon(onPressed:()=>context.push('/client/booking-details/$_bookingId'),icon:const Icon(Icons.calendar_month_outlined),label:Text(t('open_booking'))))]]));}
 Widget _statusCard(String status)=>Card(color:AppColors.primaryLight,child:Padding(padding:const EdgeInsets.all(14),child:Row(children:[const Icon(Icons.info_outline,color:AppColors.primary),const SizedBox(width:10),Expanded(child:Text(_statusLabel(status),style:const TextStyle(fontWeight:FontWeight.bold,color:AppColors.primary)))]));
 String _statusLabel(String status){switch(status){case 'open':return t('status_open_desc');case 'matching':return t('status_matching_desc');case 'booked':return t('status_booked_desc');case 'in_progress':return t('status_in_progress_desc');case 'completed':return t('status_completed_desc');case 'cancelled':return t('status_cancelled_desc');default:return status;}}
 String _careTypeKey(String value)=>{'elderly':'care_elderly','post_surgery':'care_post_surgery','chronic_disease':'care_chronic','disability':'care_disability','maternity':'care_maternity','general':'care_general'}[value]??value;
 String _serviceKey(String value)=>{'متابعة الحالة':'service_followup','إعطاء الأدوية':'service_medication','قياس الضغط':'service_bp','قياس السكر':'service_glucose','تغيير الجروح':'service_wound','مساعدة الحركة':'service_mobility','رعاية كبار السن':'service_elderly','رعاية ما بعد العمليات':'service_post_surgery'}[value]??value;
 String _governorate(String value){const en={'القاهرة':'Cairo','الجيزة':'Giza','الإسكندرية':'Alexandria','القليوبية':'Qalyubia','الدقهلية':'Dakahlia','الشرقية':'Sharqia','الغربية':'Gharbia','المنوفية':'Monufia','البحيرة':'Beheira','كفر الشيخ':'Kafr El Sheikh','دمياط':'Damietta','بورسعيد':'Port Said','الإسماعيلية':'Ismailia','السويس':'Suez','الفيوم':'Fayoum','بني سويف':'Beni Suef','المنيا':'Minya','أسيوط':'Assiut','سوهاج':'Sohag','قنا':'Qena','الأقصر':'Luxor','أسوان':'Aswan','مطروح':'Matrouh','الوادي الجديد':'New Valley','شمال سيناء':'North Sinai','جنوب سيناء':'South Sinai','البحر الأحمر':'Red Sea'};return LocaleController.instance.isEnglish?(en[value]??value):value;}
 Widget _row(String label,String value)=>Padding(padding:const EdgeInsets.symmetric(vertical:5),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[SizedBox(width:100,child:Text(label,style:const TextStyle(fontWeight:FontWeight.bold))),Expanded(child:Text(value))])); }
